import {
  PharmaAsset,
  Mechanism,
  Combination,
  Biomarker,
  CompetitorAlert,
  DataSource,
  AgenticWorkflow,
  ResearchInsight,
  PharmaMetrics,
} from '@/types/knowledge';

export const mockPharmaAssets: PharmaAsset[] = [
  {
    id: 'bct-301',
    compoundId: 'BCT-301',
    name: 'Tigelatumab',
    phase: 'phase-3',
    indication: 'Non-Small Cell Lung Cancer (NSCLC)',
    moa: 'PD-L1 x TIGIT Dual Checkpoint Inhibitor',
    riskScore: 3.2,
    nextMilestone: 'FDA PDUFA date',
    milestoneDate: new Date('2026-03-15'),
    trialIds: ['NCT05234567', 'NCT05345678'],
  },
  {
    id: 'bct-402',
    compoundId: 'BCT-402',
    name: 'Lagvimab',
    phase: 'phase-2',
    indication: 'Melanoma',
    moa: 'LAG-3 Monoclonal Antibody',
    riskScore: 4.8,
    nextMilestone: 'Phase II interim readout',
    milestoneDate: new Date('2025-12-20'),
    trialIds: ['NCT05456789', 'NCT05567890'],
  },
  {
    id: 'bct-508',
    compoundId: 'BCT-508',
    name: 'Stimaxol',
    phase: 'phase-2',
    indication: 'Solid Tumors',
    moa: 'STING Pathway Agonist',
    riskScore: 5.1,
    nextMilestone: 'Dose escalation complete',
    milestoneDate: new Date('2025-11-30'),
    trialIds: ['NCT05678901', 'NCT05789012'],
  },
  {
    id: 'bct-155',
    compoundId: 'BCT-155',
    name: 'Cedratuzumab',
    phase: 'phase-1',
    indication: 'Acute Myeloid Leukemia (AML)',
    moa: 'CD47 Macrophage Checkpoint Inhibitor',
    riskScore: 6.3,
    nextMilestone: 'Phase Ib expansion',
    milestoneDate: new Date('2026-05-15'),
    trialIds: ['NCT05890123'],
  },
  {
    id: 'bct-612',
    compoundId: 'BCT-612',
    name: 'Adenobloc',
    phase: 'phase-1',
    indication: 'Solid Tumors',
    moa: 'A2A/A2B Adenosine Receptor Antagonist',
    riskScore: 6.7,
    nextMilestone: 'Safety review milestone',
    milestoneDate: new Date('2026-02-28'),
    trialIds: ['NCT05901234'],
  },
  {
    id: 'bct-089',
    compoundId: 'BCT-089',
    name: 'Transformab',
    phase: 'preclinical',
    indication: 'Pancreatic Cancer',
    moa: 'TGF-β Pathway Inhibitor',
    riskScore: 7.2,
    nextMilestone: 'IND filing',
    milestoneDate: new Date('2026-09-30'),
  },
  {
    id: 'bct-744',
    compoundId: 'BCT-744',
    name: 'TIL-Boost',
    phase: 'preclinical',
    indication: 'Multiple Solid Tumors',
    moa: 'TIL Enhancement Platform',
    riskScore: 7.5,
    nextMilestone: 'Lead optimization',
  },
  {
    id: 'bct-931',
    compoundId: 'BCT-931',
    name: 'SpatioTarget-1',
    phase: 'discovery',
    indication: 'Breast Cancer',
    moa: 'Spatial Biology Target',
    riskScore: 8.4,
  },
  {
    id: 'bct-822',
    compoundId: 'BCT-822',
    name: 'Immunex-V2',
    phase: 'discovery',
    indication: 'Colorectal Cancer',
    moa: 'Next-Gen Checkpoint Modulator',
    riskScore: 8.1,
  },
  {
    id: 'bct-733',
    compoundId: 'BCT-733',
    name: 'CAR-NK Platform',
    phase: 'discovery',
    indication: 'Hematologic Malignancies',
    moa: 'CAR-NK Cell Therapy',
    riskScore: 8.8,
  },
  {
    id: 'bct-644',
    compoundId: 'BCT-644',
    name: 'OncoVac-IO',
    phase: 'discovery',
    indication: 'Glioblastoma',
    moa: 'Personalized Cancer Vaccine',
    riskScore: 9.2,
  },
  {
    id: 'bct-555',
    compoundId: 'BCT-555',
    name: 'BiTE-Alpha',
    phase: 'discovery',
    indication: 'B-cell Lymphoma',
    moa: 'Bispecific T-cell Engager',
    riskScore: 8.6,
  },
];

export const mockMechanisms: Mechanism[] = [
  {
    id: 'mech-1',
    title: 'TIGIT + LAG-3 Dual Blockade Synergy',
    target: 'TIGIT / LAG-3',
    journal: 'Nature Immunology',
    publishedDate: new Date('2025-08-15'),
    evidenceScore: 9.4,
    publicationCount: 47,
    trialCount: 12,
    priority: 'high',
    timeline: {
      milestones: [
        {
          type: 'publication',
          date: new Date('2022-03-15'),
          label: 'First study',
          description: 'Dual blockade concept published in Science Immunology',
        },
        {
          type: 'patent',
          date: new Date('2023-06-20'),
          label: 'Patent wave',
          description: 'Major pharma filed 8 patents on bispecific approaches',
        },
        {
          type: 'trial',
          date: new Date('2024-01-10'),
          label: 'Phase I start',
          description: 'BMS initiated first-in-human trial',
        },
        {
          type: 'trial',
          date: new Date('2025-08-15'),
          label: '12 active trials',
          description: 'Multiple Phase I/II trials ongoing',
        },
        {
          type: 'prediction',
          date: new Date('2026-04-30'),
          label: 'Phase III data',
          description: 'First Phase III interim readout expected',
          isPrediction: true,
        },
      ],
      predictedNextMilestone: {
        type: 'clinical',
        label: 'First Phase III interim analysis',
        predictedDate: new Date('2026-04-30'),
        confidence: 'high',
        rationale: 'Based on current trial enrollment rates and typical NSCLC trial timelines.',
      },
    },
    evidenceTrajectory: [
      { date: new Date('2024-04-01'), score: 7.2, publicationCount: 18, trialCount: 4 },
      { date: new Date('2024-07-01'), score: 7.8, publicationCount: 25, trialCount: 6 },
      { date: new Date('2024-10-01'), score: 8.4, publicationCount: 32, trialCount: 8 },
      { date: new Date('2025-01-01'), score: 8.9, publicationCount: 38, trialCount: 10 },
      { date: new Date('2025-04-01'), score: 9.1, publicationCount: 42, trialCount: 11 },
      { date: new Date('2025-07-01'), score: 9.3, publicationCount: 45, trialCount: 12 },
      { date: new Date('2025-10-01'), score: 9.4, publicationCount: 47, trialCount: 12 },
    ],
    competitivePositioning: {
      yourPosition: 'fast-follower',
      competitors: [
        { company: 'Bristol Myers Squibb', position: 'leader', assets: ['BMS-986789'], phase: 'Phase I' },
        { company: 'Merck', position: 'leader', assets: ['Pembro + Favezelimab'], phase: 'Phase III' },
        { company: 'Roche', position: 'fast-follower', assets: ['RO7247669'], phase: 'Phase I/II' },
        { company: 'BioCure (You)', position: 'fast-follower', assets: ['BCT-301'], phase: 'Phase III' },
      ],
      marketGaps: ['H&N cancer underexplored', 'Biomarker selection not optimized', 'Dosing schedule opportunities'],
      competitiveAdvantage: 'BCT-301 combination may offer better tolerability vs. bispecific formats',
    },
    detailedAnalysis: {
      pathwayAnalysis: 'TIGIT and LAG-3 are co-inhibitory receptors on T cells and NK cells that suppress anti-tumor immunity through distinct but complementary mechanisms. TIGIT binds CD155/CD112 on tumor cells while LAG-3 binds MHC class II. Dual blockade creates synergistic immune activation by removing multiple brakes simultaneously.',
      keyPublications: [
        {
          title: 'Synergistic effects of dual TIGIT and LAG-3 blockade in preclinical models',
          authors: 'Zhang et al.',
          journal: 'Nature Immunology',
          year: 2025,
          pmid: '38901234',
          keyFinding: '73% tumor regression vs 28% for PD-1 alone in mouse models',
        },
        {
          title: 'TIGIT/LAG-3 co-expression predicts checkpoint therapy resistance',
          authors: 'Rodriguez-Martinez et al.',
          journal: 'Cancer Cell',
          year: 2024,
          pmid: '38234567',
          keyFinding: 'Dual expression identifies subset with <10% ORR on PD-1 monotherapy',
        },
        {
          title: 'Phase I safety and efficacy of BMS-986789 bispecific antibody',
          authors: 'Chen et al.',
          journal: 'Clinical Cancer Research',
          year: 2025,
          keyFinding: 'Well-tolerated, 42% ORR in dose escalation cohort',
        },
      ],
      activeCompetitors: [
        {
          company: 'Bristol Myers Squibb',
          asset: 'BMS-986789',
          phase: 'Phase I',
          indication: 'NSCLC, Melanoma',
          differentiator: 'Bispecific format (single molecule)',
        },
        {
          company: 'Merck',
          asset: 'Pembrolizumab + Favezelimab',
          phase: 'Phase III',
          indication: 'Melanoma, NSCLC',
          differentiator: 'Combo of approved PD-1 + LAG-3',
        },
        {
          company: 'Roche',
          asset: 'Tiragolumab + Atezolizumab',
          phase: 'Phase II/III',
          indication: 'NSCLC',
          differentiator: 'TIGIT with PD-L1',
        },
      ],
      commercialPotential: {
        marketSize: '$8.2B by 2030 (dual checkpoint segment)',
        growthRate: '24% CAGR (2025-2030)',
        competitiveIntensity: 'high',
        aiAssessment: 'High commercial potential driven by checkpoint resistance population (40-60% of NSCLC). Market will support 3-4 players with differentiation on efficacy, safety, and dosing convenience.',
      },
    },
  },
  {
    id: 'mech-2',
    title: 'Gut Microbiome Modulation Enhances Checkpoint Efficacy',
    target: 'Microbiome-Immune Axis',
    journal: 'Cell',
    publishedDate: new Date('2025-09-10'),
    evidenceScore: 9.1,
    publicationCount: 34,
    trialCount: 8,
    priority: 'high',
    timeline: {
      milestones: [
        {
          type: 'publication',
          date: new Date('2021-11-10'),
          label: 'Breakthrough study',
          description: 'Microbiome impact on checkpoint response published in Science',
        },
        {
          type: 'trial',
          date: new Date('2023-05-15'),
          label: 'First FMT trial',
          description: 'Fecal microbiota transplant trial initiated',
        },
        {
          type: 'trial',
          date: new Date('2025-02-20'),
          label: '8 active trials',
          description: 'Multiple microbiome modulation approaches in clinic',
        },
        {
          type: 'prediction',
          date: new Date('2026-09-15'),
          label: 'Phase II data',
          description: 'First controlled microbiome intervention results',
          isPrediction: true,
        },
      ],
      predictedNextMilestone: {
        type: 'clinical',
        label: 'Phase II microbiome modulation results',
        predictedDate: new Date('2026-09-15'),
        confidence: 'medium',
        rationale: 'Microbiome trials have variable timelines due to patient heterogeneity and intervention complexity.',
      },
    },
    evidenceTrajectory: [
      { date: new Date('2024-04-01'), score: 6.8, publicationCount: 15, trialCount: 3 },
      { date: new Date('2024-07-01'), score: 7.3, publicationCount: 20, trialCount: 4 },
      { date: new Date('2024-10-01'), score: 7.8, publicationCount: 24, trialCount: 5 },
      { date: new Date('2025-01-01'), score: 8.1, publicationCount: 28, trialCount: 6 },
      { date: new Date('2025-04-01'), score: 8.4, publicationCount: 31, trialCount: 7 },
      { date: new Date('2025-07-01'), score: 8.7, publicationCount: 34, trialCount: 8 },
      { date: new Date('2025-10-01'), score: 9.1, publicationCount: 34, trialCount: 8 },
    ],
    competitivePositioning: {
      yourPosition: 'emerging',
      competitors: [
        { company: 'Seres Therapeutics', position: 'leader', assets: ['SER-401'], phase: 'Phase II' },
        { company: 'Evelo Biosciences', position: 'leader', assets: ['EDP1815'], phase: 'Phase II' },
        { company: 'BioCure (You)', position: 'emerging', assets: ['BCT-MIC-01'], phase: 'Preclinical' },
      ],
      marketGaps: ['Predictive biomarkers needed', 'Standardization of interventions', 'Personalized approaches'],
      competitiveAdvantage: 'Early stage positioning allows learning from competitor trials',
    },
    detailedAnalysis: {
      pathwayAnalysis: 'The gut microbiome influences systemic immunity through metabolite production, immune cell education, and barrier function. Specific bacterial strains produce short-chain fatty acids and other metabolites that modulate T cell differentiation and checkpoint expression, directly impacting immunotherapy efficacy.',
      keyPublications: [
        {
          title: 'Gut microbiome composition predicts checkpoint inhibitor response',
          authors: 'Routy et al.',
          journal: 'Science',
          year: 2021,
          keyFinding: 'Akkermansia muciniphila associated with better response rates',
        },
        {
          title: 'Fecal microbiota transplantation overcomes resistance to PD-1 blockade',
          authors: 'Baruch et al.',
          journal: 'Cell',
          year: 2024,
          keyFinding: 'FMT from responders restored checkpoint response in refractory patients',
        },
        {
          title: 'Microbiome metabolites regulate T cell exhaustion',
          authors: 'Nomura et al.',
          journal: 'Nature Immunology',
          year: 2025,
          keyFinding: 'Butyrate production reduces PD-1 expression on CD8+ T cells',
        },
      ],
      activeCompetitors: [
        {
          company: 'Seres Therapeutics',
          asset: 'SER-401',
          phase: 'Phase II',
          indication: 'Melanoma + Keytruda',
          differentiator: 'Defined bacterial consortium',
        },
        {
          company: 'Evelo Biosciences',
          asset: 'EDP1815',
          phase: 'Phase II',
          indication: 'Multiple cancers',
          differentiator: 'Single-strain approach',
        },
      ],
      commercialPotential: {
        marketSize: '$2.8B by 2032 (microbiome oncology)',
        growthRate: '32% CAGR (2025-2032)',
        competitiveIntensity: 'medium',
        aiAssessment: 'Emerging field with high potential but significant development challenges around standardization and regulatory pathway. Early movers with strong clinical data will capture premium positioning.',
      },
    },
  },
  {
    id: 'mech-3',
    title: 'Tumor-Resident Memory T-cell Activation',
    target: 'TRM cells',
    journal: 'Science',
    publishedDate: new Date('2025-07-22'),
    evidenceScore: 8.7,
    publicationCount: 29,
    trialCount: 0,
    priority: 'medium',
  },
  {
    id: 'mech-4',
    title: 'Spatial Transcriptomics Reveals Immune Exclusion Patterns',
    target: 'TME Architecture',
    journal: 'Nature',
    publishedDate: new Date('2025-09-05'),
    evidenceScore: 9.3,
    publicationCount: 41,
    trialCount: 6,
    priority: 'high',
  },
  {
    id: 'mech-5',
    title: 'STING Pathway Synergy with Radiotherapy',
    target: 'cGAS-STING',
    journal: 'Cancer Discovery',
    publishedDate: new Date('2025-08-28'),
    evidenceScore: 8.4,
    publicationCount: 23,
    trialCount: 4,
    priority: 'medium',
  },
  {
    id: 'mech-6',
    title: 'CD47 Blockade in Hematologic Malignancies',
    target: 'CD47-SIRPα',
    journal: 'Blood',
    publishedDate: new Date('2025-09-18'),
    evidenceScore: 8.9,
    publicationCount: 38,
    trialCount: 9,
    priority: 'high',
  },
  {
    id: 'mech-7',
    title: 'Adenosine Pathway Modulation in TME',
    target: 'A2A/A2B Receptors',
    journal: 'Immunity',
    publishedDate: new Date('2025-08-12'),
    evidenceScore: 8.2,
    publicationCount: 31,
    trialCount: 7,
    priority: 'medium',
  },
  {
    id: 'mech-8',
    title: 'Optimal TGF-β Blockade Timing in Pancreatic Cancer',
    target: 'TGF-β Signaling',
    journal: 'Journal of Clinical Investigation',
    publishedDate: new Date('2025-07-30'),
    evidenceScore: 7.8,
    publicationCount: 19,
    trialCount: 0,
    priority: 'medium',
  },
];

export const mockCombinations: Combination[] = [
  {
    id: 'combo-1',
    drugPair: 'BCT-301 + PARP inhibitor',
    indication: 'NSCLC (BRCA-wild)',
    evidenceScore: 8.9,
    publicationCount: 24,
    activeTrials: ['NCT05234567', 'NCT05445678', 'NCT05556789'],
    synergy: 'DNA damage + immune activation',
  },
  {
    id: 'combo-2',
    drugPair: 'BCT-301 + Metformin',
    indication: 'NSCLC / Colorectal',
    evidenceScore: 8.7,
    publicationCount: 31,
    activeTrials: ['NCT05667890'],
    synergy: 'Metabolic reprogramming + checkpoint',
  },
  {
    id: 'combo-3',
    drugPair: 'BCT-402 + Radiation',
    indication: 'Melanoma',
    evidenceScore: 8.4,
    publicationCount: 18,
    activeTrials: ['NCT05778901', 'NCT05889012'],
    synergy: 'Immunogenic cell death',
  },
  {
    id: 'combo-4',
    drugPair: 'BCT-508 + Anti-PD-1',
    indication: 'Solid Tumors',
    evidenceScore: 9.2,
    publicationCount: 42,
    activeTrials: ['NCT05990123', 'NCT06001234', 'NCT06112345', 'NCT06223456', 'NCT06334567'],
    synergy: 'Innate + adaptive immunity',
  },
  {
    id: 'combo-5',
    drugPair: 'BCT-155 + Azacitidine',
    indication: 'AML',
    evidenceScore: 8.1,
    publicationCount: 27,
    activeTrials: ['NCT06445678', 'NCT06556789', 'NCT06667890', 'NCT06778901'],
    synergy: 'Epigenetic + phagocytosis',
  },
  {
    id: 'combo-6',
    drugPair: 'BCT-612 + Carboplatin',
    indication: 'NSCLC',
    evidenceScore: 7.8,
    publicationCount: 19,
    activeTrials: ['NCT06889012', 'NCT06990123'],
    synergy: 'Chemotherapy + TME modulation',
  },
  {
    id: 'combo-7',
    drugPair: 'PD-L1 + Oncolytic Virus',
    indication: 'Multiple Solid Tumors',
    evidenceScore: 7.6,
    publicationCount: 23,
    activeTrials: ['NCT07001234', 'NCT07112345', 'NCT07223456'],
    synergy: 'Viral immunogenicity + checkpoint',
  },
  {
    id: 'combo-8',
    drugPair: 'LAG-3 + Gut Microbiome Modulation',
    indication: 'Colorectal Cancer',
    evidenceScore: 7.3,
    publicationCount: 15,
    activeTrials: ['NCT07334567'],
    synergy: 'Microbiome-immune axis',
  },
  {
    id: 'combo-9',
    drugPair: 'STING Agonist + Anti-VEGF',
    indication: 'Solid Tumors',
    evidenceScore: 7.1,
    publicationCount: 17,
    activeTrials: ['NCT07445678', 'NCT07556789'],
    synergy: 'Vascular normalization + inflammation',
  },
  {
    id: 'combo-10',
    drugPair: 'CD47 Blocker + Venetoclax',
    indication: 'AML',
    evidenceScore: 6.9,
    publicationCount: 21,
    activeTrials: ['NCT07667890', 'NCT07778901', 'NCT07889012'],
    synergy: 'Phagocytosis + BCL-2 inhibition',
  },
];

export const mockBiomarkers: Biomarker[] = [
  {
    id: 'bio-1',
    name: 'TMB (Tumor Mutational Burden)',
    relatedAsset: 'BCT-301',
    application: 'Patient selection for checkpoint therapy',
    evidenceCount: 89,
    priority: 'high',
  },
  {
    id: 'bio-2',
    name: 'PD-L1 + LAG-3 Co-expression',
    relatedAsset: 'BCT-402',
    application: 'Dual checkpoint responder identification',
    evidenceCount: 34,
    priority: 'high',
  },
  {
    id: 'bio-3',
    name: 'cGAS-STING Pathway Activation Signature',
    relatedAsset: 'BCT-508',
    application: 'STING agonist efficacy predictor',
    evidenceCount: 41,
    priority: 'high',
  },
  {
    id: 'bio-4',
    name: 'CD47 Surface Expression Levels',
    relatedAsset: 'BCT-155',
    application: 'Dosing optimization and response monitoring',
    evidenceCount: 52,
    priority: 'medium',
  },
  {
    id: 'bio-5',
    name: 'A2A Receptor Density in TME',
    relatedAsset: 'BCT-612',
    application: 'Adenosine pathway blockade response',
    evidenceCount: 28,
    priority: 'medium',
  },
  {
    id: 'bio-6',
    name: 'TGF-β Signaling Signature',
    relatedAsset: 'BCT-089',
    application: 'Target engagement and dose selection',
    evidenceCount: 31,
    priority: 'high',
  },
];

export const mockCompetitorAlerts: CompetitorAlert[] = [
  {
    id: 'alert-1',
    company: 'Bristol Myers Squibb',
    event: 'IND filing for LAG-3 + TIGIT dual blocker',
    details: 'BMS filed IND for novel bispecific antibody targeting LAG-3 and TIGIT simultaneously. Direct competitor to BCT-301 dual checkpoint approach. Phase I expected to start Q1 2026 with dose escalation in NSCLC patients. MOA overlap: 85%. Patent US20250345678A1 filed.',
    impact: 'high',
    date: new Date('2025-09-28'),
    relatedAssets: ['BCT-301'],
    trialId: 'NCT05789012',
    patentNumber: 'US20250345678A1',
  },
  {
    id: 'alert-2',
    company: 'Merck',
    event: 'Positive Phase III interim data for LAG-3 combo',
    details: 'Merck reported positive Phase III interim analysis for pembrolizumab + favezelimab (LAG-3) in melanoma. ORR: 52% vs 38% control arm (p=0.003), median PFS: 12.4 months vs 8.1 months. Could accelerate approval timeline and increase competitive pressure on BCT-402.',
    impact: 'high',
    date: new Date('2025-09-15'),
    relatedAssets: ['BCT-402'],
    trialId: 'NCT04567890',
  },
  {
    id: 'alert-3',
    company: 'Roche',
    event: 'Patent filing for CD47 + PD-L1 bispecific',
    details: 'Roche filed patent for bispecific antibody targeting CD47 and PD-L1. Claims cover combination approaches in AML and solid tumors. Potential FTO (freedom-to-operate) concern for BCT-155 combination strategies. Patent family includes 12 dependent claims covering dosing regimens.',
    impact: 'medium',
    date: new Date('2025-09-22'),
    relatedAssets: ['BCT-155'],
    patentNumber: 'US20250234567A1',
  },
  {
    id: 'alert-4',
    company: 'Pfizer',
    event: 'Acquisition of STING agonist startup',
    details: 'Pfizer acquired Immunova Therapeutics ($340M upfront + $890M milestones) for lead STING agonist asset. Phase II expected 2026 in pancreatic cancer. Validates STING pathway but increases competitive landscape for BCT-508. Pfizer has significant oncology development capabilities.',
    impact: 'medium',
    date: new Date('2025-09-10'),
    relatedAssets: ['BCT-508'],
  },
  {
    id: 'alert-5',
    company: 'AstraZeneca',
    event: 'Expanded indication approval for durvalumab combo',
    details: 'FDA approved durvalumab + tremelimumab for first-line pancreatic cancer based on HIMALAYA-2 trial results. Establishes new SOC (standard of care) for pancreatic cancer, raising bar for BCT-089 TGF-β inhibitor development. Trial showed 18.2 month median OS.',
    impact: 'medium',
    date: new Date('2025-08-30'),
    relatedAssets: ['BCT-089'],
  },
  {
    id: 'alert-6',
    company: 'Novartis',
    event: 'TGF-β trap Phase I data at ESMO 2025',
    details: 'Novartis presented Phase I data for NVS-TGF890 at ESMO. Well-tolerated at doses up to 800mg Q3W, dose escalation ongoing. Early signals of tumor shrinkage in 4/18 evaluable patients with pancreatic cancer. Competitive validation of TGF-β pathway.',
    impact: 'low',
    date: new Date('2025-09-25'),
    relatedAssets: ['BCT-089'],
  },
];

export const mockPharmaDataSources: DataSource[] = [
  {
    id: 'pds-1',
    name: 'ClinicalTrials.gov',
    type: 'clinical',
    status: 'connected',
    category: 'Clinical Intelligence',
    icon: 'Activity',
    authType: 'api-key',
    isAuthenticated: true,
    isPrimary: true,
    lastSync: new Date('2025-10-02T08:00:00'),
    stats: {
      papersIndexed: 445678,
      queryLimit: { used: 4230, total: 5000 },
    },
    features: ['Trial monitoring', 'Enrollment tracking', 'Results analysis', 'Competitor trials'],
    appMode: 'pharma',
  },
  {
    id: 'pds-2',
    name: 'PubMed',
    type: 'academic',
    status: 'connected',
    category: 'Biomedical Literature',
    icon: 'BookOpen',
    authType: 'api-key',
    isAuthenticated: true,
    lastSync: new Date('2025-10-02T07:30:00'),
    stats: {
      papersIndexed: 36000000,
      queryLimit: { used: 1240, total: 5000 },
    },
    features: ['MeSH search', 'BioCure alerts', 'Competitor tracking', 'MOA discovery'],
    appMode: 'pharma',
  },
  {
    id: 'pds-3',
    name: 'Google Patents',
    type: 'patent',
    status: 'connected',
    category: 'IP Intelligence',
    icon: 'Shield',
    authType: 'api-key',
    isAuthenticated: true,
    lastSync: new Date('2025-10-01T22:00:00'),
    stats: {
      papersIndexed: 23,
    },
    features: ['Patent monitoring', 'Citation networks', 'FTO analysis', 'Competitor filings'],
    appMode: 'pharma',
  },
  {
    id: 'pds-4',
    name: 'Cortellis',
    type: 'commercial',
    status: 'connected',
    category: 'Competitive Intelligence',
    icon: 'TrendingUp',
    authType: 'oauth',
    isAuthenticated: true,
    lastSync: new Date('2025-10-02T06:00:00'),
    stats: {
      papersIndexed: 156,
    },
    features: ['Pipeline tracking', 'Deal intelligence', 'Phase transitions', 'Market analysis'],
    appMode: 'pharma',
  },
  {
    id: 'pds-5',
    name: 'FDA Drugs@FDA',
    type: 'regulatory',
    status: 'connected',
    category: 'Regulatory Intelligence',
    icon: 'FileCheck',
    authType: 'none',
    isAuthenticated: true,
    lastSync: new Date('2025-10-02T09:15:00'),
    features: ['Approval tracking', 'Label updates', 'PDUFA dates', 'Orphan designations'],
    appMode: 'pharma',
  },
  {
    id: 'pds-6',
    name: 'EMA Clinical Data',
    type: 'regulatory',
    status: 'available',
    category: 'European Regulatory',
    icon: 'Globe',
    authType: 'api-key',
    isAuthenticated: false,
    features: ['EMA submissions', 'CHMP opinions', 'European trials', 'Safety data'],
    appMode: 'pharma',
  },
  {
    id: 'pds-7',
    name: 'PharmaProjects',
    type: 'commercial',
    status: 'suggested',
    category: 'Pipeline Database',
    icon: 'Database',
    authType: 'oauth',
    isAuthenticated: false,
    features: ['Global pipeline', 'Licensing deals', 'Mergers & acquisitions', 'Technology platforms'],
    appMode: 'pharma',
  },
];

export const mockPharmaWorkflows: AgenticWorkflow[] = [
  {
    id: 'pwf-1',
    name: 'Competitor IO Pipeline Tracker',
    description: 'Monitor BMS, Merck, Roche publications and trial updates in immuno-oncology',
    status: 'active',
    trigger: {
      type: 'time',
      config: { cron: '0 8 * * *' },
    },
    nodes: [],
    edges: [],
    lastRun: new Date('2025-10-02T08:00:00'),
    nextRun: new Date('2025-10-03T08:00:00'),
    stats: {
      totalRuns: 142,
      successRate: 98.2,
      papersProcessed: 89,
    },
    createdAt: new Date('2025-05-01'),
    updatedAt: new Date('2025-10-02'),
    appMode: 'pharma',
  },
  {
    id: 'pwf-2',
    name: 'Novel MOA Discovery Engine',
    description: 'Scan Nature, Science, Cell for breakthrough immunotherapy mechanisms',
    status: 'active',
    trigger: {
      type: 'time',
      config: { cron: '0 10 * * 1' },
    },
    nodes: [],
    edges: [],
    lastRun: new Date('2025-10-01T10:00:00'),
    nextRun: new Date('2025-10-08T10:00:00'),
    stats: {
      totalRuns: 89,
      successRate: 96.8,
      papersProcessed: 234,
    },
    createdAt: new Date('2025-06-10'),
    updatedAt: new Date('2025-10-01'),
    appMode: 'pharma',
  },
  {
    id: 'pwf-3',
    name: 'BCT-301 Citation Alert',
    description: 'Track all mentions of BCT-301 (Tigelatumab) in literature and conferences',
    status: 'active',
    trigger: {
      type: 'time',
      config: { cron: '0 18 * * *' },
    },
    nodes: [],
    edges: [],
    lastRun: new Date('2025-10-02T18:00:00'),
    nextRun: new Date('2025-10-03T18:00:00'),
    stats: {
      totalRuns: 67,
      successRate: 100,
      papersProcessed: 34,
    },
    createdAt: new Date('2025-07-01'),
    updatedAt: new Date('2025-10-02'),
    appMode: 'pharma',
  },
  {
    id: 'pwf-4',
    name: 'Patent Landscape Scanner',
    description: 'Monitor USPTO and EPO filings in checkpoint and TGF-β space',
    status: 'active',
    trigger: {
      type: 'time',
      config: { cron: '0 9 * * 2' },
    },
    nodes: [],
    edges: [],
    lastRun: new Date('2025-09-30T09:00:00'),
    nextRun: new Date('2025-10-07T09:00:00'),
    stats: {
      totalRuns: 54,
      successRate: 94.3,
      papersProcessed: 23,
    },
    createdAt: new Date('2025-04-15'),
    updatedAt: new Date('2025-09-30'),
    appMode: 'pharma',
  },
];

export const mockPharmaInsights: ResearchInsight[] = [
  {
    id: 'pi-1',
    type: 'competitive-threat',
    title: 'Bristol Myers Squibb filed IND for LAG-3 + TIGIT dual blocker',
    description: 'Direct BCT-301 competitor with bispecific approach. Phase I expected Q1 2026. MOA overlap: 85%. Patent US20250345678A1 covers similar epitope binding.',
    actionLabel: 'View full alert',
    priority: 'high',
    createdAt: new Date('2025-09-28'),
    appMode: 'pharma',
    strategicAnalysis: {
      whyMatters: 'This represents a direct competitive threat to BCT-301 with a potentially superior bispecific format that could offer better efficacy and dosing convenience. BMS has proven immuno-oncology development capabilities and strong regulatory relationships that could accelerate their timeline. The high MOA overlap means head-to-head comparisons will be inevitable in physician decision-making.',
      competitiveContext: 'BMS joins Merck, Roche, and Regeneron in developing dual checkpoint inhibitors targeting this mechanism. BMS has successfully launched Opdivo (PD-1) and Yervoy (CTLA-4), demonstrating commercial execution strength. Their bispecific format may offer PK/PD advantages over our combination approach. Patent landscape analysis shows they have strong IP coverage in the bispecific space.',
      marketOpportunity: {
        description: 'NSCLC checkpoint inhibitor market projected at $18.5B by 2028, with dual checkpoint inhibitors expected to capture 30-40% share based on improved response rates.',
        marketSize: '$5.5-7.4B addressable for dual checkpoint space',
        unmetNeed: '58% of NSCLC patients do not respond to first-line PD-1/PD-L1 monotherapy',
      },
      recommendedActions: [
        {
          action: 'Assess BCT-301 combination potential with CD47 inhibitor (BCT-155) to create differentiation',
          priority: 'immediate',
          owner: 'Clinical Development',
        },
        {
          action: 'File defensive patents covering dosing schedules and patient selection biomarkers',
          priority: 'immediate',
          owner: 'IP Team',
        },
        {
          action: 'Accelerate Phase III enrollment by opening 15 additional sites in Europe',
          priority: 'near-term',
          owner: 'Clinical Operations',
        },
        {
          action: 'Evaluate partnership opportunities with PD-L1 leaders for co-marketing rights',
          priority: 'monitor',
          owner: 'Business Development',
        },
      ],
      timelineImpact: {
        description: 'BMS IND filing puts pressure on our PDUFA timeline. If they achieve breakthrough designation, they could reach market 12-18 months ahead of our projected approval.',
        milestoneEffect: 'critical-path',
        estimatedImpact: 'Need to accelerate Phase III readout by 6 months to maintain competitive position',
      },
    },
    scores: {
      opportunityScore: 6,
      urgency: 'high',
      competitiveThreat: 'critical',
    },
  },
  {
    id: 'pi-2',
    type: 'pipeline-opportunity',
    title: 'Novel STING + anti-PD-L1 synergy data in Cancer Discovery',
    description: 'Preclinical study shows 73% tumor regression in STING agonist + checkpoint combo. BCT-508 combination potential with partnered PD-L1 inhibitor.',
    actionLabel: 'Create workflow',
    priority: 'high',
    createdAt: new Date('2025-09-25'),
    appMode: 'pharma',
    strategicAnalysis: {
      whyMatters: 'This preclinical data provides strong scientific rationale for combining BCT-508 (STING agonist) with checkpoint inhibitors. The 73% tumor regression rate significantly exceeds monotherapy benchmarks (20-30%) and suggests potential best-in-class combination opportunity. This could be transformative for BCT-508 development strategy.',
      competitiveContext: 'Pfizer recently acquired a STING agonist for $340M upfront, validating commercial interest. However, most competitors are pursuing STING monotherapy while we could differentiate with combination strategy. GSK and Merck have checkpoint inhibitors actively seeking combination partners. This positions BCT-508 favorably for partnerships.',
      marketOpportunity: {
        description: 'STING agonist market nascent but growing rapidly. Combination approaches could address cold tumor phenotype affecting 40% of solid tumor patients who fail checkpoint inhibitors.',
        marketSize: '$3.2B opportunity in checkpoint-refractory solid tumors by 2030',
        unmetNeed: '40% of patients have immunologically cold tumors with poor checkpoint response',
      },
      recommendedActions: [
        {
          action: 'Initiate BCT-508 + pembrolizumab combination cohort in ongoing Phase Ib trial',
          priority: 'immediate',
          owner: 'Clinical Development',
        },
        {
          action: 'Approach Merck BD team regarding co-development agreement for melanoma indication',
          priority: 'immediate',
          owner: 'Business Development',
        },
        {
          action: 'File provisional patent on combination dosing schedule and patient selection criteria',
          priority: 'near-term',
          owner: 'IP Team',
        },
      ],
      timelineImpact: {
        description: 'Combination strategy could accelerate development by leveraging existing checkpoint inhibitor approvals. Potential for breakthrough designation based on preliminary ORR data.',
        milestoneEffect: 'accelerates',
        estimatedImpact: 'Could advance timeline by 12-18 months vs. monotherapy development',
      },
    },
    scores: {
      opportunityScore: 9,
      urgency: 'high',
      competitiveThreat: 'low',
    },
  },
  {
    id: 'pi-3',
    type: 'market-shift',
    title: 'FDA draft guidance on accelerated IO approvals',
    description: 'New guidance requires biomarker-driven patient selection for accelerated approvals in immuno-oncology. Impacts BCT-301 BLA strategy - TMB companion diagnostic may be required.',
    actionLabel: 'Review guidance',
    priority: 'high',
    createdAt: new Date('2025-09-20'),
    appMode: 'pharma',
    strategicAnalysis: {
      whyMatters: 'FDA draft guidance fundamentally changes regulatory path for checkpoint inhibitors. Requiring companion diagnostics adds development complexity and cost but could also enable premium pricing and market differentiation. Early adoption of biomarker strategy could position BCT-301 ahead of competitors still pursuing all-comers approaches.',
      competitiveContext: 'Merck and BMS have established relationships with diagnostic partners (Foundation Medicine, Guardant). We lack CDx partnerships which puts us at disadvantage. However, competitors with ongoing trials may need protocol amendments causing delays we can avoid by proactive planning.',
      marketOpportunity: {
        description: 'Precision oncology market growing 12% CAGR. Biomarker-selected patients show 2x higher response rates, supporting premium pricing.',
        marketSize: 'Targeted NSCLC segment: $4.2B (23% of total NSCLC market)',
        unmetNeed: 'TMB-high patients (15-20% of NSCLC) have limited options after PD-1 progression',
      },
      recommendedActions: [
        {
          action: 'Engage Foundation Medicine and Guardant for CDx partnership discussions',
          priority: 'immediate',
          owner: 'Regulatory Affairs / BD',
        },
        {
          action: 'Initiate retrospective TMB analysis on BCT-301 Phase II samples to identify optimal cutoff',
          priority: 'immediate',
          owner: 'Translational Medicine',
        },
        {
          action: 'Submit formal meeting request with FDA Division of Oncology Products to discuss CDx strategy',
          priority: 'near-term',
          owner: 'Regulatory Affairs',
        },
      ],
      timelineImpact: {
        description: 'Companion diagnostic development typically adds 12-18 months to BLA submission. However, FDA may grant accelerated approval path for biomarker-selected populations with lower efficacy bar.',
        milestoneEffect: 'delays',
        estimatedImpact: '12-18 month CDx development, but potential for earlier accelerated approval',
      },
    },
    scores: {
      opportunityScore: 7,
      urgency: 'high',
      competitiveThreat: 'moderate',
    },
  },
  {
    id: 'pi-4',
    type: 'biomarker-discovery',
    title: 'Spatial transcriptomics identifies BCT-402 response signature',
    description: 'TIL density patterns in tumor periphery predict LAG-3 inhibitor response with 84% accuracy. Potential companion diagnostic for BCT-402 patient selection.',
    actionLabel: 'View publication',
    priority: 'medium',
    createdAt: new Date('2025-09-18'),
    appMode: 'pharma',
    strategicAnalysis: {
      whyMatters: 'High-accuracy predictive biomarker could transform BCT-402 from moderate efficacy drug to best-in-class in defined patient population. 84% prediction accuracy exceeds industry standard (70-75%) for companion diagnostics. Spatial profiling approach aligns with emerging regulatory preference for mechanistic biomarkers.',
      competitiveContext: 'Merck and BMS pursuing similar spatial profiling approaches for their LAG-3 programs. Nanostring and 10x Genomics competing for spatial biology platform dominance. Early partner selection critical to secure platform access and establish IP position in biomarker space.',
      marketOpportunity: {
        description: 'Biomarker-enriched melanoma population represents focused commercial opportunity with higher pricing potential and clearer label differentiation.',
        marketSize: '$850M in TIL-high melanoma segment (35% of total melanoma market)',
        unmetNeed: 'Post-PD-1 melanoma patients with high TIL density lack targeted options',
      },
      recommendedActions: [
        {
          action: 'Validate spatial TIL signature in BCT-402 Phase II samples with independent pathology review',
          priority: 'immediate',
          owner: 'Translational Medicine',
        },
        {
          action: 'Initiate CDx partnership discussions with Nanostring and 10x Genomics',
          priority: 'near-term',
          owner: 'Business Development',
        },
        {
          action: 'Design prospective biomarker validation cohort in ongoing Phase II trial',
          priority: 'near-term',
          owner: 'Clinical Development',
        },
      ],
      timelineImpact: {
        description: 'Prospective validation adds 6-9 months to Phase II but creates clear regulatory path to approval. Biomarker-driven label could support premium pricing and reduce Phase III sample size requirements.',
        milestoneEffect: 'neutral',
        estimatedImpact: 'Short-term delay offset by faster Phase III and stronger commercial profile',
      },
    },
    scores: {
      opportunityScore: 8,
      urgency: 'medium',
      competitiveThreat: 'moderate',
    },
  },
  {
    id: 'pi-5',
    type: 'competitive-threat',
    title: 'Merck Phase III interim data for LAG-3 combo in NSCLC',
    description: 'Positive interim analysis: ORR 52% vs 38% (p=0.003), median PFS 12.4 vs 8.1 months. Accelerates competitive timeline for BCT-402 melanoma program.',
    actionLabel: 'View trial data',
    priority: 'medium',
    createdAt: new Date('2025-09-15'),
    appMode: 'pharma',
    strategicAnalysis: {
      whyMatters: 'Strong clinical validation of LAG-3 pathway in solid tumors increases likelihood of FDA approval for Merck combo, establishing new standard of care. BCT-402 differentiation will need to focus on melanoma indication and potentially biomarker-selected populations to avoid direct competition.',
      competitiveContext: 'Merck likely to file NDA Q2 2026 with approval possible by Q4 2026. Their pembrolizumab franchise gives them strong KOL relationships and commercial infrastructure. BMS also developing LAG-3 combo. Market consolidating around 2-3 LAG-3 leaders, making speed to market critical.',
      marketOpportunity: {
        description: 'Melanoma LAG-3 market less crowded than NSCLC. Opportunity to establish early presence before Merck expands label to melanoma indication.',
        marketSize: '$1.2B in post-PD-1 melanoma by 2028',
        unmetNeed: '30% of melanoma patients progress on PD-1 therapy within first year',
      },
      recommendedActions: [
        {
          action: 'Focus BCT-402 development exclusively on melanoma to avoid head-to-head NSCLC competition',
          priority: 'immediate',
          owner: 'Clinical Strategy',
        },
        {
          action: 'Accelerate Phase II melanoma cohort enrollment to generate data for Q2 2026 ASH presentation',
          priority: 'immediate',
          owner: 'Clinical Operations',
        },
        {
          action: 'Explore acquisition of complementary melanoma asset to build franchise',
          priority: 'monitor',
          owner: 'Corporate Development',
        },
      ],
      timelineImpact: {
        description: 'Merck approval likely by Q4 2026 establishes competitive benchmark. BCT-402 Phase II data needed by mid-2026 to maintain relevance. May need to pivot from NSCLC to melanoma as lead indication.',
        milestoneEffect: 'neutral',
        estimatedImpact: 'No major timeline change but strategic repositioning required',
      },
    },
    scores: {
      opportunityScore: 5,
      urgency: 'medium',
      competitiveThreat: 'high',
    },
  },
  {
    id: 'pi-6',
    type: 'pipeline-opportunity',
    title: 'PARP inhibitor + immunotherapy shows 68% ORR in BRCA-wild NSCLC',
    description: 'ASCO 2025 presentation shows dramatic response in non-BRCA population. BCT-301 + PARP combo expansion opportunity beyond current BRCA-mutant focus.',
    actionLabel: 'Analyze data',
    priority: 'medium',
    createdAt: new Date('2025-09-12'),
    appMode: 'pharma',
    strategicAnalysis: {
      whyMatters: 'Expansion into BRCA-wild population dramatically increases addressable market for PARP combos from 15% to 85% of NSCLC patients. Mechanistically validates synthetic lethality approach beyond DNA repair deficiency. Creates major combination opportunity for BCT-301.',
      competitiveContext: 'AstraZeneca (Lynparza), Merck, and GSK all exploring PARP + IO combinations. Most current trials focus on BRCA-mutant patients. BRCA-wild data is early but could trigger competitive rush to initiate similar trials. First-mover advantage in trial initiation critical.',
      marketOpportunity: {
        description: 'BRCA-wild NSCLC represents massive untapped market for PARP combinations. Could position BCT-301 + PARP as backbone therapy across broad NSCLC population.',
        marketSize: '$6.8B opportunity in BRCA-wild NSCLC (85% of total NSCLC market)',
        unmetNeed: 'BRCA-wild patients currently excluded from PARP therapy despite synthetic lethality mechanisms',
      },
      recommendedActions: [
        {
          action: 'Add BRCA-wild expansion cohort to ongoing BCT-301 + olaparib Phase Ib/II trial',
          priority: 'immediate',
          owner: 'Clinical Development',
        },
        {
          action: 'Initiate BD discussions with AstraZeneca regarding expanded Lynparza collaboration',
          priority: 'near-term',
          owner: 'Business Development',
        },
        {
          action: 'File provisional patent on biomarker-free PARP + checkpoint combination approach',
          priority: 'near-term',
          owner: 'IP Team',
        },
      ],
      timelineImpact: {
        description: 'BRCA-wild expansion cohort adds 6 months to Phase II timeline but unlocks significantly larger Phase III opportunity. Could justify larger Phase III investment and faster enrollment.',
        milestoneEffect: 'accelerates',
        estimatedImpact: 'Short-term 6 month delay enables 5x larger commercial opportunity',
      },
    },
    scores: {
      opportunityScore: 8,
      urgency: 'medium',
      competitiveThreat: 'moderate',
    },
  },
];

export const mockPharmaMetrics: PharmaMetrics = {
  competitiveThreats: 89,
  pipelineOpportunities: 34,
  patentsMonitored: 156,
  marketSignals: 47,
};
