import { TrendDataPoint } from '@/types/horizon';

export const mockTrendScatterData: TrendDataPoint[] = [
  {
    id: 'trend-1',
    name: 'Federated Learning in Healthcare',
    publicationActivity: 42,
    citationVelocity: 156,
    activeResearchers: 234,
    maturityStage: 'growing',
    methodology: 'computational',
    aiSummary: 'Privacy-preserving machine learning is revolutionizing clinical research by enabling collaborative model training across institutions without sharing sensitive patient data. Rapid adoption in oncology and rare disease studies.',
    extendedAnalysis: 'Federated learning has emerged as a transformative approach in healthcare AI, addressing critical privacy concerns while enabling large-scale collaborative research. Recent implementations in multi-institutional oncology trials have demonstrated equivalent model performance to centralized approaches while maintaining HIPAA compliance. The technology is particularly impactful in rare disease research where data scarcity has historically limited AI applications. Current challenges include heterogeneous data quality across sites and communication overhead, though recent algorithmic advances are mitigating these issues.',
    details: {
      topAuthors: ['Dr. Sarah Chen', 'Dr. Michael Rodriguez', 'Dr. Aisha Patel'],
      recentPapers: 67,
      growthRate: 145,
    },
  },
  {
    id: 'trend-2',
    name: 'CRISPR Base Editing',
    publicationActivity: 38,
    citationVelocity: 189,
    activeResearchers: 456,
    maturityStage: 'established',
    methodology: 'experimental',
    aiSummary: 'Precise single-nucleotide editing without double-strand breaks has become the gold standard for therapeutic gene correction. Clinical trials for sickle cell disease showing promising results.',
    extendedAnalysis: 'Base editing represents the evolution of CRISPR technology beyond traditional gene knockout, enabling precise C-to-T and A-to-G conversions without creating double-strand breaks. This approach significantly reduces off-target effects and cellular toxicity. Recent clinical trials in sickle cell disease and beta-thalassemia have shown remarkable efficacy, with patients achieving transfusion independence. The technology is now being adapted for in vivo applications, with liver-directed therapies showing early promise in animal models.',
    details: {
      topAuthors: ['Dr. David Liu', 'Dr. Jennifer Doudna', 'Dr. Feng Zhang'],
      recentPapers: 123,
      growthRate: 78,
    },
  },
  {
    id: 'trend-3',
    name: 'Quantum Annealing for Drug Discovery',
    publicationActivity: 12,
    citationVelocity: 34,
    activeResearchers: 67,
    maturityStage: 'nascent',
    methodology: 'computational',
    aiSummary: 'Emerging quantum computing approaches are being explored for molecular optimization and protein folding predictions. Still in early stages but showing theoretical advantages over classical methods.',
    extendedAnalysis: 'Quantum annealing is being investigated as a novel approach to solve computationally intractable problems in drug discovery, particularly molecular conformational sampling and binding affinity optimization. While current quantum hardware remains limited in qubit count and coherence time, proof-of-concept studies have demonstrated potential advantages in exploring chemical space more efficiently than classical algorithms. The field is highly speculative but attracting significant pharmaceutical industry investment.',
    details: {
      topAuthors: ['Dr. Alan Aspuru-Guzik', 'Dr. Morten Kjaergaard'],
      recentPapers: 18,
      growthRate: 234,
    },
  },
  {
    id: 'trend-4',
    name: 'Spatial Transcriptomics',
    publicationActivity: 35,
    citationVelocity: 142,
    activeResearchers: 312,
    maturityStage: 'growing',
    methodology: 'experimental',
    aiSummary: 'Combining gene expression profiling with spatial context is transforming tissue biology understanding. Particularly impactful in tumor microenvironment characterization and developmental biology.',
    extendedAnalysis: 'Spatial transcriptomics platforms have evolved from low-resolution array-based methods to single-cell and even subcellular resolution imaging-based approaches. This technology is revolutionizing our understanding of tissue architecture and cellular communication in health and disease. In oncology, spatial transcriptomics is revealing previously hidden tumor microenvironment heterogeneity and identifying novel therapeutic targets. The integration with single-cell RNA-seq and proteomics data is enabling unprecedented multi-modal tissue analysis.',
    details: {
      topAuthors: ['Dr. Joakim Lundeberg', 'Dr. Evan Macosko', 'Dr. Long Cai'],
      recentPapers: 89,
      growthRate: 167,
    },
  },
  {
    id: 'trend-5',
    name: 'AI-Driven Protein Design',
    publicationActivity: 28,
    citationVelocity: 98,
    activeResearchers: 189,
    maturityStage: 'emerging',
    methodology: 'computational',
    aiSummary: 'Deep learning models are enabling de novo design of proteins with novel functions. AlphaFold and RoseTTAFold successors are pushing boundaries in therapeutic protein engineering.',
    extendedAnalysis: 'Building on the success of structure prediction models like AlphaFold2, the field has rapidly advanced to generative protein design. Novel architectures can now design proteins with specified functions, binding specificities, or structural properties from scratch. Recent successes include de novo enzyme design, novel binding proteins, and self-assembling nanomaterials. The technology is being applied to create next-generation biologics with improved properties and entirely new therapeutic modalities.',
    details: {
      topAuthors: ['Dr. David Baker', 'Dr. Demis Hassabis', 'Dr. Mohammed AlQuraishi'],
      recentPapers: 56,
      growthRate: 198,
    },
  },
  {
    id: 'trend-6',
    name: 'Organoid-on-a-Chip Systems',
    publicationActivity: 24,
    citationVelocity: 87,
    activeResearchers: 145,
    maturityStage: 'emerging',
    methodology: 'experimental',
    aiSummary: 'Microfluidic platforms hosting patient-derived organoids are enabling personalized drug testing and disease modeling. Bridging gap between in vitro and in vivo studies.',
    extendedAnalysis: 'Organoid-on-a-chip technology combines 3D organoid culture with microfluidic control to recreate physiological microenvironments and organ-organ interactions. These systems are proving invaluable for personalized medicine applications, allowing patient-specific drug screening before treatment. Recent advances include multi-organ chips that model systemic drug metabolism and toxicity. The technology is particularly promising for rare disease research and drug development where animal models are limited.',
    details: {
      topAuthors: ['Dr. Donald Ingber', 'Dr. Jianhua Qin', 'Dr. Noo Li Jeon'],
      recentPapers: 43,
      growthRate: 156,
    },
  },
  {
    id: 'trend-7',
    name: 'Single-Cell Multi-Omics',
    publicationActivity: 44,
    citationVelocity: 167,
    activeResearchers: 378,
    maturityStage: 'growing',
    methodology: 'experimental',
    aiSummary: 'Simultaneous measurement of multiple molecular layers in individual cells reveals unprecedented cellular heterogeneity. Critical for understanding cell state transitions and disease mechanisms.',
    extendedAnalysis: 'Multi-omic profiling at single-cell resolution is uncovering the complex relationships between genomic, transcriptomic, epigenomic, and proteomic layers. Technologies like CITE-seq, ASAP-seq, and TEA-seq enable simultaneous measurement of RNA and protein, chromatin accessibility and transcription, or even all three. These approaches are revealing how gene regulatory networks operate and how cells make fate decisions during development and disease progression.',
    details: {
      topAuthors: ['Dr. Aviv Regev', 'Dr. Sarah Teichmann', 'Dr. Rahul Satija'],
      recentPapers: 94,
      growthRate: 142,
    },
  },
  {
    id: 'trend-8',
    name: 'Neuromorphic Computing for Biomedical AI',
    publicationActivity: 9,
    citationVelocity: 28,
    activeResearchers: 52,
    maturityStage: 'nascent',
    methodology: 'computational',
    aiSummary: 'Brain-inspired computing architectures promise energy-efficient processing for real-time biomedical signal analysis. Early explorations in wearable diagnostics and neuroprosthetics.',
    extendedAnalysis: 'Neuromorphic chips that mimic neural architecture offer potential solutions to the energy constraints of edge AI in medical devices. Spiking neural networks running on these chips can process biosignals with orders of magnitude less power than conventional processors. Applications in development include real-time seizure detection, cardiac arrhythmia monitoring, and brain-machine interfaces. The field is still nascent with most work in proof-of-concept stage.',
    details: {
      topAuthors: ['Dr. Giacomo Indiveri', 'Dr. Kwabena Boahen'],
      recentPapers: 14,
      growthRate: 267,
    },
  },
  {
    id: 'trend-9',
    name: 'mRNA Vaccine Platforms',
    publicationActivity: 47,
    citationVelocity: 178,
    activeResearchers: 523,
    maturityStage: 'established',
    methodology: 'clinical',
    aiSummary: 'COVID-19 success has catalyzed rapid expansion to cancer, infectious disease, and rare disease applications. Platform technology enabling rapid vaccine development.',
    extendedAnalysis: 'The clinical success of mRNA vaccines for COVID-19 has validated the platform and accelerated development across numerous therapeutic areas. Personalized cancer vaccines targeting patient-specific neoantigens are showing promising clinical results. The technology is being adapted for vaccines against HIV, malaria, and influenza, with several candidates in late-stage trials. Manufacturing improvements and novel lipid nanoparticle formulations are addressing stability and delivery challenges.',
    details: {
      topAuthors: ['Dr. Katalin Karikó', 'Dr. Drew Weissman', 'Dr. Uğur Şahin'],
      recentPapers: 156,
      growthRate: 89,
    },
  },
  {
    id: 'trend-10',
    name: 'Microbiome Metabolomics',
    publicationActivity: 31,
    citationVelocity: 112,
    activeResearchers: 267,
    maturityStage: 'emerging',
    methodology: 'experimental',
    aiSummary: 'Comprehensive profiling of microbial metabolites reveals host-microbiome interactions critical for health and disease. Links emerging to neurological and metabolic disorders.',
    extendedAnalysis: 'Mass spectrometry-based metabolomics is revealing the vast chemical diversity produced by the human microbiome and its impact on host physiology. Recent studies have identified specific microbial metabolites that modulate immune function, influence brain chemistry, and affect drug metabolism. The gut-brain axis is particularly active area, with metabolites like short-chain fatty acids showing effects on neuroinflammation and behavior. Therapeutic strategies targeting microbiome metabolism are in early clinical development.',
    details: {
      topAuthors: ['Dr. Justin Sonnenburg', 'Dr. Eran Elinav', 'Dr. Michael Fischbach'],
      recentPapers: 67,
      growthRate: 178,
    },
  },
  {
    id: 'trend-11',
    name: 'Synthetic Biology Gene Circuits',
    publicationActivity: 26,
    citationVelocity: 94,
    activeResearchers: 198,
    maturityStage: 'growing',
    methodology: 'experimental',
    aiSummary: 'Engineered genetic circuits enable programmable cellular behaviors for diagnostics and therapeutics. Living therapeutics with logic-gated responses showing clinical promise.',
    extendedAnalysis: 'Synthetic biology is moving from simple gene expression control to sophisticated genetic circuits with sensing, processing, and actuation capabilities. CAR-T cells with AND-gate logic for improved tumor selectivity are in clinical trials. Engineered bacteria capable of detecting and treating gut inflammation demonstrate the potential of living diagnostics and therapeutics. The field is developing standardized genetic parts and design principles for more reliable circuit engineering.',
    details: {
      topAuthors: ['Dr. Christopher Voigt', 'Dr. James Collins', 'Dr. Timothy Lu'],
      recentPapers: 52,
      growthRate: 187,
    },
  },
  {
    id: 'trend-12',
    name: 'Digital Twins for Personalized Medicine',
    publicationActivity: 19,
    citationVelocity: 73,
    activeResearchers: 134,
    maturityStage: 'emerging',
    methodology: 'computational',
    aiSummary: 'Patient-specific computational models enable in silico treatment simulation and optimization. Integration of multi-scale data from molecular to organ level.',
    extendedAnalysis: 'Digital twin technology in medicine involves creating computational replicas of individual patients that integrate genomic, physiological, and imaging data. These models can simulate disease progression and treatment responses, potentially enabling truly personalized therapy selection. Cardiac digital twins are most advanced, with models predicting arrhythmia risk and optimal pacing strategies. Cancer digital twins incorporating genomic evolution and drug resistance mechanisms are in development. Major challenges include model validation and real-time data integration.',
    details: {
      topAuthors: ['Dr. Natalia Trayanova', 'Dr. Kristin Swanson', 'Dr. Paul Macklin'],
      recentPapers: 38,
      growthRate: 203,
    },
  },
  {
    id: 'trend-13',
    name: 'Cryo-EM Structure Determination',
    publicationActivity: 41,
    citationVelocity: 158,
    activeResearchers: 412,
    maturityStage: 'established',
    methodology: 'experimental',
    aiSummary: 'Near-atomic resolution structures of biomolecules in native states revolutionizing structural biology. Critical tool for drug discovery and understanding molecular mechanisms.',
    extendedAnalysis: 'Cryo-electron microscopy has matured into a routine technique for determining structures of large protein complexes, membrane proteins, and dynamic assemblies that resist crystallization. Recent advances in detector technology and image processing algorithms have pushed resolution limits below 2Å for some samples. The technology is essential for structure-based drug design, with recent successes including COVID-19 spike protein inhibitors. Time-resolved cryo-EM is emerging to capture conformational dynamics and enzymatic mechanisms.',
    details: {
      topAuthors: ['Dr. Yifan Cheng', 'Dr. Sjors Scheres', 'Dr. Eva Nogales'],
      recentPapers: 187,
      growthRate: 67,
    },
  },
  {
    id: 'trend-14',
    name: 'CAR-T Cell Therapy Optimization',
    publicationActivity: 36,
    citationVelocity: 145,
    activeResearchers: 389,
    maturityStage: 'established',
    methodology: 'clinical',
    aiSummary: 'Next-generation CAR designs with improved safety, persistence, and solid tumor efficacy. Allogeneic "off-the-shelf" products entering clinical testing.',
    extendedAnalysis: 'CAR-T therapy has evolved from proof-of-concept to standard-of-care for several hematologic malignancies. Current research focuses on improving CAR design with optimized signaling domains, incorporating safety switches, and enhancing T cell fitness through metabolic engineering. Major efforts target solid tumors where challenges include tumor infiltration, immunosuppressive microenvironment, and antigen heterogeneity. Allogeneic CAR-T products using gene editing to prevent rejection could dramatically improve accessibility and reduce costs.',
    details: {
      topAuthors: ['Dr. Carl June', 'Dr. Michel Sadelain', 'Dr. Crystal Mackall'],
      recentPapers: 142,
      growthRate: 76,
    },
  },
  {
    id: 'trend-15',
    name: 'Liquid Biopsy Diagnostics',
    publicationActivity: 39,
    citationVelocity: 134,
    activeResearchers: 356,
    maturityStage: 'growing',
    methodology: 'clinical',
    aiSummary: 'Blood-based detection of cancer and disease biomarkers enabling minimally invasive monitoring. Circulating tumor DNA analysis guiding treatment decisions in real-time.',
    extendedAnalysis: 'Liquid biopsy technology analyzes circulating tumor DNA, RNA, proteins, and cells from blood samples to detect cancer, monitor treatment response, and identify resistance mechanisms. Clinical validation studies have demonstrated utility in tracking minimal residual disease after surgery and detecting relapse months before imaging. Next-generation sequencing and digital PCR enable detection of mutations at ultra-low frequencies. Multi-cancer early detection tests are in large-scale validation trials. The technology is expanding beyond oncology to prenatal testing and organ transplant monitoring.',
    details: {
      topAuthors: ['Dr. Maximilian Diehn', 'Dr. Victor Velculescu', 'Dr. Nitzan Rosenfeld'],
      recentPapers: 98,
      growthRate: 156,
    },
  },
  {
    id: 'trend-16',
    name: 'Exosome-Based Drug Delivery',
    publicationActivity: 22,
    citationVelocity: 81,
    activeResearchers: 167,
    maturityStage: 'emerging',
    methodology: 'experimental',
    aiSummary: 'Natural nanovesicles engineered for targeted therapeutic delivery with low immunogenicity. Crossing blood-brain barrier and targeting specific cell types.',
    extendedAnalysis: 'Exosomes are being developed as natural drug delivery vehicles with advantages over synthetic nanoparticles including biocompatibility and intrinsic targeting capabilities. Engineering approaches include loading with therapeutic RNA or proteins, surface modification for enhanced targeting, and isolation from different cell sources for specific applications. Brain-derived exosomes show promise for CNS drug delivery. Clinical trials are testing exosome-delivered therapeutics for cancer and neurodegenerative diseases.',
    details: {
      topAuthors: ['Dr. Tushar Patel', 'Dr. Xandra Breakefield', 'Dr. Raghu Kalluri'],
      recentPapers: 47,
      growthRate: 192,
    },
  },
  {
    id: 'trend-17',
    name: 'AI-Powered Clinical Trial Design',
    publicationActivity: 27,
    citationVelocity: 96,
    activeResearchers: 203,
    maturityStage: 'emerging',
    methodology: 'computational',
    aiSummary: 'Machine learning optimizing patient selection, endpoint design, and adaptive trial protocols. Reducing trial costs and improving success rates.',
    extendedAnalysis: 'Artificial intelligence is being applied across the clinical trial lifecycle to improve efficiency and success rates. ML models can identify optimal patient populations using real-world data, predict enrollment rates, and simulate trial outcomes. Adaptive trial designs use interim data to modify protocols in real-time. Natural language processing extracts relevant information from medical records for patient screening. Digital biomarkers and remote monitoring enabled by AI are creating new endpoints and reducing site visits.',
    details: {
      topAuthors: ['Dr. Nigam Shah', 'Dr. Isaac Kohane', 'Dr. Marinka Zitnik'],
      recentPapers: 54,
      growthRate: 189,
    },
  },
  {
    id: 'trend-18',
    name: 'RNA Interference Therapeutics',
    publicationActivity: 33,
    citationVelocity: 124,
    activeResearchers: 298,
    maturityStage: 'established',
    methodology: 'clinical',
    aiSummary: 'FDA-approved siRNA drugs validating RNA-targeted therapeutics. Expanding to new disease areas with improved delivery technologies.',
    extendedAnalysis: 'RNA interference therapeutics have achieved clinical success with multiple FDA-approved drugs for rare genetic diseases and hypercholesterolemia. GalNAc conjugation has solved delivery challenges for liver-targeted applications, achieving potent and durable gene silencing. Research is expanding to CNS applications using intrathecal delivery and exploring other tissue targets. Combination with gene editing and oligonucleotide therapies is creating new therapeutic strategies. The platform is being applied to infectious diseases and cancer.',
    details: {
      topAuthors: ['Dr. Phillip Zamore', 'Dr. Dinah Sah', 'Dr. Anastasia Khvorova'],
      recentPapers: 89,
      growthRate: 98,
    },
  },
  {
    id: 'trend-19',
    name: 'Senolytic Drug Development',
    publicationActivity: 21,
    citationVelocity: 78,
    activeResearchers: 156,
    maturityStage: 'emerging',
    methodology: 'experimental',
    aiSummary: 'Therapies targeting senescent cells showing promise for age-related diseases. Clinical trials in idiopathic pulmonary fibrosis and osteoarthritis underway.',
    extendedAnalysis: 'Senolytic drugs selectively eliminate senescent cells that accumulate with age and drive chronic inflammation and tissue dysfunction. Initial clinical trials have shown improvements in physical function and biomarkers of inflammation in elderly patients. The approach is being tested across multiple age-related conditions including frailty, Alzheimer\'s disease, and metabolic disorders. Challenges include identifying optimal senolytic agents, dosing regimens, and patient selection. Biomarkers of cellular senescence are being validated for treatment monitoring.',
    details: {
      topAuthors: ['Dr. James Kirkland', 'Dr. Judith Campisi', 'Dr. Jan van Deursen'],
      recentPapers: 44,
      growthRate: 201,
    },
  },
  {
    id: 'trend-20',
    name: 'Brain-Computer Interfaces',
    publicationActivity: 29,
    citationVelocity: 107,
    activeResearchers: 234,
    maturityStage: 'growing',
    methodology: 'experimental',
    aiSummary: 'Direct neural interfaces enabling communication and control for paralyzed patients. Wireless implantable systems with thousands of electrodes entering trials.',
    extendedAnalysis: 'Brain-computer interface technology has progressed from laboratory demonstrations to clinical applications, with FDA-approved devices for paralysis patients enabling communication and computer control. Recent advances include wireless fully-implantable systems, high-density electrode arrays, and machine learning decoders that adapt to neural signals over time. Applications are expanding beyond motor control to sensory feedback, memory enhancement, and treatment of neurological disorders. Ethical frameworks for BCIs are being developed alongside the technology.',
    details: {
      topAuthors: ['Dr. Krishna Shenoy', 'Dr. Edward Chang', 'Dr. Leigh Hochberg'],
      recentPapers: 63,
      growthRate: 167,
    },
  },
];
