import {
  AgenticWorkflow,
  DataSource,
  WorkflowPerformance,
  ResearchInsight,
  AnalyticsSnapshot,
  SystemMode,
  WorkflowTemplate,
} from '@/types/knowledge';
import { mockPharmaDataSources } from './mockPharmaData';

export const mockWorkflows: AgenticWorkflow[] = [
  {
    id: 'wf-1',
    name: 'Daily arXiv AI Research Monitor',
    description: 'Automatically fetch and summarize new AI/ML papers from arXiv every morning',
    status: 'active',
    trigger: {
      type: 'time',
      config: { cron: '0 9 * * *' },
    },
    nodes: [],
    edges: [],
    lastRun: new Date('2025-10-01T09:00:00'),
    nextRun: new Date('2025-10-03T09:00:00'),
    stats: {
      totalRuns: 127,
      successRate: 98.4,
      papersProcessed: 1842,
    },
    createdAt: new Date('2025-06-15'),
    updatedAt: new Date('2025-10-01'),
    appMode: 'researcher',
  },
  {
    id: 'wf-2',
    name: 'Citation Alert Tracker',
    description: 'Monitor new citations to your publications and notify when thresholds are met',
    status: 'active',
    trigger: {
      type: 'time',
      config: { cron: '0 18 * * 1' },
    },
    nodes: [],
    edges: [],
    lastRun: new Date('2025-09-30T18:00:00'),
    nextRun: new Date('2025-10-07T18:00:00'),
    stats: {
      totalRuns: 24,
      successRate: 100,
      papersProcessed: 89,
    },
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date('2025-09-30'),
    appMode: 'researcher',
  },
  {
    id: 'wf-3',
    name: 'Weekly Dimensions Literature Review',
    description: 'Comprehensive review of publications in your field from Dimensions database',
    status: 'paused',
    trigger: {
      type: 'time',
      config: { cron: '0 10 * * 5' },
    },
    nodes: [],
    edges: [],
    lastRun: new Date('2025-09-20T10:00:00'),
    stats: {
      totalRuns: 18,
      successRate: 94.4,
      papersProcessed: 456,
    },
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-09-20'),
    appMode: 'researcher',
  },
];

const researcherDataSources: DataSource[] = [
  {
    id: 'ds-1',
    name: 'Dimensions',
    type: 'academic',
    status: 'connected',
    category: 'Primary Database',
    icon: 'Database',
    authType: 'api-key',
    isAuthenticated: true,
    isPrimary: true,
    lastSync: new Date('2025-10-02T08:30:00'),
    stats: {
      papersIndexed: 142789654,
      queryLimit: { used: 3240, total: 10000 },
    },
    features: ['Full-text search', 'Citation analysis', 'Author profiles', 'Field classification'],
    appMode: 'researcher',
  },
  {
    id: 'ds-2',
    name: 'arXiv',
    type: 'academic',
    status: 'connected',
    category: 'Preprint Repository',
    icon: 'FileText',
    authType: 'none',
    isAuthenticated: true,
    lastSync: new Date('2025-10-02T09:00:00'),
    stats: {
      papersIndexed: 2456789,
    },
    features: ['Open access', 'Daily updates', 'Category filtering', 'PDF downloads'],
    appMode: 'researcher',
  },
  {
    id: 'ds-3',
    name: 'PubMed',
    type: 'academic',
    status: 'connected',
    category: 'Biomedical Database',
    icon: 'Microscope',
    authType: 'api-key',
    isAuthenticated: true,
    lastSync: new Date('2025-10-01T22:15:00'),
    stats: {
      papersIndexed: 36000000,
      queryLimit: { used: 850, total: 5000 },
    },
    features: ['MeSH terms', 'Clinical trials', 'Systematic reviews', 'Author search'],
    appMode: 'researcher',
  },
  {
    id: 'ds-4',
    name: 'Kaggle Datasets',
    type: 'web',
    status: 'connected',
    category: 'Dataset Repository',
    icon: 'BarChart3',
    authType: 'oauth',
    isAuthenticated: true,
    lastSync: new Date('2025-10-02T07:45:00'),
    stats: {
      datasetsAvailable: 3,
    },
    features: ['Dataset search', 'Competition access', 'Notebook integration', 'Download datasets'],
    trending: {
      datasets: [
        {
          id: 'kg-1',
          name: 'Cancer RNA-seq Expression Data',
          source: 'Kaggle',
          downloads: 12543,
          relevanceScore: 0.94,
        },
        {
          id: 'kg-2',
          name: 'Clinical Trial Outcomes 2024',
          source: 'Kaggle',
          downloads: 8932,
          relevanceScore: 0.87,
        },
      ],
    },
    appMode: 'researcher',
  },
  {
    id: 'ds-5',
    name: 'Europe PMC',
    type: 'academic',
    status: 'available',
    category: 'Biomedical Database',
    icon: 'Globe',
    authType: 'api-key',
    isAuthenticated: false,
    features: ['Open access', 'Full-text articles', 'Data citations', 'Grant information'],
    appMode: 'researcher',
  },
  {
    id: 'ds-6',
    name: 'bioRxiv',
    type: 'academic',
    status: 'available',
    category: 'Preprint Repository',
    icon: 'FlaskConical',
    authType: 'none',
    isAuthenticated: false,
    features: ['Biology preprints', 'Peer review', 'Version tracking', 'Open access'],
    appMode: 'researcher',
  },
  {
    id: 'ds-7',
    name: 'CORE',
    type: 'academic',
    status: 'suggested',
    category: 'Aggregator',
    icon: 'Archive',
    authType: 'api-key',
    isAuthenticated: false,
    features: ['Open access aggregation', '200M+ papers', 'Full-text search', 'API access'],
    appMode: 'researcher',
  },
  {
    id: 'ds-8',
    name: 'Institutional Knowledge Graph',
    type: 'institutional',
    status: 'connected',
    category: 'Custom',
    icon: 'Network',
    authType: 'sso',
    isAuthenticated: true,
    lastSync: new Date('2025-10-02T06:00:00'),
    features: ['Internal publications', 'Collaboration networks', 'Grant tracking', 'Custom ontology'],
    appMode: 'researcher',
  },
];

// Merge researcher and pharma data sources
export const mockDataSources: DataSource[] = [...researcherDataSources, ...mockPharmaDataSources];

export const mockWorkflowPerformance: WorkflowPerformance[] = [
  {
    workflowId: 'wf-1',
    workflowName: 'Daily arXiv AI Research Monitor',
    successRate: 98.4,
    avgExecutionTime: 145,
    totalRuns: 127,
    lastRun: new Date('2025-10-01T09:00:00'),
    errorCount: 2,
  },
  {
    workflowId: 'wf-2',
    workflowName: 'Citation Alert Tracker',
    successRate: 100,
    avgExecutionTime: 89,
    totalRuns: 24,
    lastRun: new Date('2025-09-30T18:00:00'),
    errorCount: 0,
  },
  {
    workflowId: 'wf-3',
    workflowName: 'Weekly Dimensions Literature Review',
    successRate: 94.4,
    avgExecutionTime: 312,
    totalRuns: 18,
    lastRun: new Date('2025-09-20T10:00:00'),
    errorCount: 1,
  },
];

export const mockResearchInsights: ResearchInsight[] = [
  {
    id: 'insight-1',
    type: 'trend',
    title: 'Transformer architectures trending in your field',
    description: 'Publications mentioning "transformer" increased 340% in the last quarter',
    priority: 'high',
    createdAt: new Date('2025-10-01'),
    appMode: 'researcher',
  },
  {
    id: 'insight-2',
    type: 'recommendation',
    title: 'Consider expanding to "federated learning" keyword',
    description: 'High overlap with your current research interests, 89% match score',
    actionLabel: 'Add to workflow',
    priority: 'medium',
    createdAt: new Date('2025-09-30'),
    appMode: 'researcher',
  },
  {
    id: 'insight-3',
    type: 'alert',
    title: 'New highly-cited paper in your domain',
    description: 'Paper by Zhang et al. reached 150 citations in 2 weeks',
    actionLabel: 'View paper',
    actionUrl: '/library/paper-123',
    priority: 'high',
    createdAt: new Date('2025-10-02'),
    appMode: 'researcher',
  },
  {
    id: 'insight-4',
    type: 'recommendation',
    title: 'New dataset available on Kaggle',
    description: 'Cancer RNA-seq Expression Data matches your research profile',
    actionLabel: 'Connect dataset',
    priority: 'medium',
    createdAt: new Date('2025-10-01'),
    appMode: 'researcher',
  },
];

export const mockAnalytics: AnalyticsSnapshot = {
  totalPapersProcessed: 2387,
  workflowsExecuted: 169,
  dataSourcesQueried: 4,
  timeSavedHours: 47.2,
  periodStart: new Date('2025-09-01'),
  periodEnd: new Date('2025-10-02'),
};

export const mockSystemModes: SystemMode[] = [
  {
    id: 'mode-1',
    name: 'Research Mode',
    description: 'Deep analysis with extensive citations and methodology focus',
    systemPrompt: 'You are a research assistant specializing in academic literature review. Focus on methodology, citations, and connections between studies. Provide detailed analysis with proper academic context.',
    preferredDataSources: ['ds-1', 'ds-2', 'ds-3'],
    activeWorkflows: ['wf-1', 'wf-3'],
    outputFormat: 'detailed',
    isDefault: true,
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2025-09-15'),
  },
  {
    id: 'mode-2',
    name: 'Writing Mode',
    description: 'Clarity-focused with emphasis on proper citations and flow',
    systemPrompt: 'You are an academic writing assistant. Prioritize clear, concise language while maintaining academic rigor. Ensure all claims are properly cited and connected.',
    preferredDataSources: ['ds-1', 'ds-2'],
    activeWorkflows: [],
    outputFormat: 'summary',
    isDefault: false,
    createdAt: new Date('2025-07-10'),
    updatedAt: new Date('2025-08-22'),
  },
  {
    id: 'mode-3',
    name: 'Review Mode',
    description: 'Critical analysis with methodology and limitations assessment',
    systemPrompt: 'You are a peer reviewer. Critically analyze methodology, identify limitations, assess reproducibility, and evaluate contribution to the field.',
    preferredDataSources: ['ds-1', 'ds-3'],
    activeWorkflows: ['wf-2'],
    outputFormat: 'bullet-points',
    isDefault: false,
    createdAt: new Date('2025-08-05'),
    updatedAt: new Date('2025-09-28'),
  },
];

export const mockWorkflowTemplates: WorkflowTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Daily arXiv Updates',
    description: 'Monitor new papers in your field from arXiv every morning',
    category: 'Monitoring',
    icon: 'Bell',
    nodes: [],
    edges: [],
    estimatedTime: '5 min',
    popularity: 342,
  },
  {
    id: 'tmpl-2',
    name: 'Citation Alert Tracker',
    description: 'Get notified when your papers receive new citations',
    category: 'Alerts',
    icon: 'TrendingUp',
    nodes: [],
    edges: [],
    estimatedTime: '3 min',
    popularity: 289,
  },
  {
    id: 'tmpl-3',
    name: 'Weekly Literature Review',
    description: 'Comprehensive weekly digest of publications in your domain',
    category: 'Review',
    icon: 'Calendar',
    nodes: [],
    edges: [],
    estimatedTime: '15 min',
    popularity: 456,
  },
  {
    id: 'tmpl-4',
    name: 'Auto-tag by Methodology',
    description: 'Automatically categorize papers by research methodology',
    category: 'Organization',
    icon: 'Tags',
    nodes: [],
    edges: [],
    estimatedTime: '8 min',
    popularity: 178,
  },
];
