import { TechnologyPoint } from '@/types/techRadar';

export const mockTechnologyPoints: TechnologyPoint[] = [
  // DRUG MODALITIES QUADRANT (270-360°)
  {
    id: 'tech-1',
    name: 'Antibody-Drug Conjugates',
    shortDescription: 'Targeted delivery of cytotoxic payloads via monoclonal antibodies',
    quadrant: 'drug-modalities',
    ring: 'adopt',
    angle: 45,
    ringOffset: 0.3,
    therapeuticArea: 'oncology',
    opportunitySize: 'transformative',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'ADCs are proven modality with multiple FDA approvals and strong commercial success. Technology has matured significantly with improved linkers and payloads. Ready for immediate development programs.',
      keyPlayers: ['Daiichi Sankyo', 'AstraZeneca', 'Genentech', 'Seagen', 'Gilead'],
      publications: [
        {
          title: 'Next-generation antibody-drug conjugates for cancer therapy',
          authors: 'Drago et al.',
          journal: 'Nature Reviews Drug Discovery',
          year: 2024,
          pmid: '38123456',
        },
      ],
      patents: [
        {
          number: 'US10934567',
          title: 'Site-specific ADC conjugation methods',
          assignee: 'Daiichi Sankyo',
          filingDate: new Date('2023-01-15'),
        },
      ],
      clinicalTrials: [
        {
          nctId: 'NCT05123456',
          title: 'Dato-DXd in HER2-low breast cancer',
          phase: 'Phase III',
          sponsor: 'Daiichi Sankyo',
          indication: 'Breast Cancer',
        },
      ],
      recommendation: 'Immediate investment recommended. Focus on novel payload optimization and biomarker-driven patient selection.',
      marketPotential: '$25B+ by 2030',
      timeToImpact: 'Immediate',
      risks: ['Manufacturing complexity', 'Payload resistance mechanisms'],
    },
  },
  {
    id: 'tech-2',
    name: 'Bispecific Antibodies',
    shortDescription: 'Dual-targeting antibodies for enhanced efficacy',
    quadrant: 'drug-modalities',
    ring: 'adopt',
    angle: 70,
    ringOffset: 0.5,
    therapeuticArea: 'oncology',
    opportunitySize: 'large',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Multiple FDA approvals validate bispecific approach. Strong clinical data in hematology and solid tumors. Manufacturing challenges largely solved.',
      keyPlayers: ['Amgen', 'Genmab', 'Regeneron', 'AbbVie'],
      publications: [
        {
          title: 'Bispecific antibodies in oncology: clinical development',
          authors: 'Labrijn et al.',
          journal: 'Nature Reviews Clinical Oncology',
          year: 2024,
        },
      ],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Develop internal platform capabilities. Focus on novel target combinations.',
      marketPotential: '$15B by 2030',
      timeToImpact: 'Immediate',
    },
  },
  {
    id: 'tech-3',
    name: 'Peptide-Drug Conjugates',
    shortDescription: 'Peptide-based targeting with drug payloads',
    quadrant: 'drug-modalities',
    ring: 'trial',
    angle: 30,
    ringOffset: 0.4,
    therapeuticArea: 'oncology',
    opportunitySize: 'medium',
    confidence: 'medium',
    previousRing: 'assess',
    changeDate: new Date('2025-06-01'),
    detailedAssessment: {
      rationale: 'Emerging alternative to ADCs with potential advantages in tumor penetration. Limited clinical data but promising preclinical results. Run POC studies.',
      keyPlayers: ['Bicycle Therapeutics', 'PeptiDream', 'Protagonist Therapeutics'],
      publications: [
        {
          title: 'Peptide drug conjugates: a new therapeutic modality',
          authors: 'Wang et al.',
          journal: 'Chemical Reviews',
          year: 2024,
        },
      ],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Initiate proof-of-concept studies. Monitor Bicycle Therapeutics clinical progress.',
      marketPotential: '$5B by 2032',
      timeToImpact: '3-4 years',
    },
  },
  {
    id: 'tech-4',
    name: 'mRNA Therapeutics',
    shortDescription: 'Protein replacement and vaccine applications',
    quadrant: 'drug-modalities',
    ring: 'assess',
    angle: 60,
    ringOffset: 0.6,
    therapeuticArea: 'infectious-diseases',
    opportunitySize: 'transformative',
    confidence: 'medium',
    detailedAssessment: {
      rationale: 'COVID vaccines validated platform but therapeutic applications face delivery challenges. Close monitoring of clinical progress needed before committing resources.',
      keyPlayers: ['Moderna', 'BioNTech', 'CureVac', 'Translate Bio'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Watch and evaluate. Assess delivery technology improvements before major investment.',
      marketPotential: '$30B+ by 2035',
      timeToImpact: '5-7 years',
    },
  },
  {
    id: 'tech-5',
    name: 'Circular RNA',
    shortDescription: 'Stable, long-lasting RNA therapeutics',
    quadrant: 'drug-modalities',
    ring: 'monitor',
    angle: 80,
    ringOffset: 0.7,
    therapeuticArea: 'cross-therapeutic',
    opportunitySize: 'large',
    confidence: 'low',
    detailedAssessment: {
      rationale: 'Early-stage technology with theoretical advantages over linear mRNA. Significant technical hurdles remain. Long-term monitoring appropriate.',
      keyPlayers: ['Orna Therapeutics', 'Laronde', 'CircRNA Therapeutics'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Monitor scientific literature. Revisit in 2-3 years as clinical data emerges.',
      marketPotential: 'Unknown - too early',
      timeToImpact: '7-10 years',
    },
  },

  // TECHNOLOGY PLATFORMS QUADRANT (0-90°)
  {
    id: 'tech-6',
    name: 'AI/ML Drug Discovery',
    shortDescription: 'Machine learning for target ID and molecule design',
    quadrant: 'technology-platforms',
    ring: 'adopt',
    angle: 40,
    ringOffset: 0.2,
    therapeuticArea: 'cross-therapeutic',
    opportunitySize: 'transformative',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Proven value in accelerating drug discovery workflows. Multiple successful partnerships and clinical candidates. Essential technology for competitive advantage.',
      keyPlayers: ['Insilico Medicine', 'Exscientia', 'Recursion', 'BenevolentAI', 'Relay Therapeutics'],
      publications: [
        {
          title: 'AI in drug discovery: 2024 landscape',
          authors: 'Vamathevan et al.',
          journal: 'Nature Reviews Drug Discovery',
          year: 2024,
        },
      ],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Build internal AI capabilities immediately. Partner with leading platforms for specific projects.',
      marketPotential: 'Enables $50B+ in R&D savings',
      timeToImpact: 'Immediate',
    },
  },
  {
    id: 'tech-7',
    name: 'High-Throughput Screening',
    shortDescription: 'Automated compound screening platforms',
    quadrant: 'technology-platforms',
    ring: 'adopt',
    angle: 65,
    ringOffset: 0.4,
    therapeuticArea: 'cross-therapeutic',
    opportunitySize: 'medium',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Mature, well-established technology critical for early discovery. Continuous improvements in miniaturization and automation.',
      keyPlayers: ['Thermo Fisher', 'PerkinElmer', 'Agilent', 'Bio-Techne'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Maintain and upgrade existing capabilities. Integrate with AI platforms.',
      marketPotential: 'Standard infrastructure',
      timeToImpact: 'Immediate',
    },
  },
  {
    id: 'tech-8',
    name: 'Generative AI for Molecules',
    shortDescription: 'AI-generated novel chemical structures',
    quadrant: 'technology-platforms',
    ring: 'trial',
    angle: 25,
    ringOffset: 0.5,
    therapeuticArea: 'cross-therapeutic',
    opportunitySize: 'transformative',
    confidence: 'medium',
    previousRing: 'assess',
    changeDate: new Date('2025-03-15'),
    detailedAssessment: {
      rationale: 'Rapid advancement in generative models. First AI-designed molecules entering clinic. High potential but requires validation. Run POC programs.',
      keyPlayers: ['Insilico Medicine', 'Generate Biomedicines', 'Absci', 'Iktos'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Launch pilot programs on 2-3 targets. Validate generated molecules in parallel with traditional approaches.',
      marketPotential: 'Could transform discovery economics',
      timeToImpact: '2-3 years',
    },
  },
  {
    id: 'tech-9',
    name: 'Spatial Biology',
    shortDescription: 'Spatial transcriptomics and proteomics',
    quadrant: 'technology-platforms',
    ring: 'trial',
    angle: 55,
    ringOffset: 0.3,
    therapeuticArea: 'oncology',
    opportunitySize: 'large',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Rapidly maturing technology providing unprecedented insights into tumor microenvironment. Multiple commercial platforms available. Validate on key programs.',
      keyPlayers: ['10x Genomics', 'NanoString', 'Vizgen', 'Akoya Biosciences'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Deploy on oncology programs. Build internal expertise through collaborations.',
      marketPotential: '$8B market by 2030',
      timeToImpact: '1-2 years',
    },
  },
  {
    id: 'tech-10',
    name: 'Quantum Computing',
    shortDescription: 'Quantum algorithms for molecular simulation',
    quadrant: 'technology-platforms',
    ring: 'monitor',
    angle: 75,
    ringOffset: 0.8,
    therapeuticArea: 'cross-therapeutic',
    opportunitySize: 'transformative',
    confidence: 'low',
    detailedAssessment: {
      rationale: 'Theoretical potential for drug discovery applications but practical quantum advantage not yet demonstrated. Very long-term horizon.',
      keyPlayers: ['IBM', 'Google', 'IonQ', 'Zapata Computing'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Monitor developments. Consider small exploratory partnerships in 3-5 years.',
      marketPotential: 'Unknown - too speculative',
      timeToImpact: '10+ years',
    },
  },

  // THERAPEUTIC APPROACHES QUADRANT (90-180°)
  {
    id: 'tech-11',
    name: 'CAR-T Cell Therapy',
    shortDescription: 'Engineered T cells for cancer immunotherapy',
    quadrant: 'therapeutic-approaches',
    ring: 'adopt',
    angle: 35,
    ringOffset: 0.3,
    therapeuticArea: 'oncology',
    opportunitySize: 'transformative',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Multiple FDA approvals in hematologic malignancies. Proven curative potential. Technology ready for next-gen improvements and solid tumor expansion.',
      keyPlayers: ['Novartis', 'Gilead/Kite', 'BMS', 'Juno/Celgene', 'Legend Biotech'],
      publications: [
        {
          title: 'CAR-T therapy: current landscape and future directions',
          authors: 'June et al.',
          journal: 'Nature Reviews Clinical Oncology',
          year: 2024,
        },
      ],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Develop next-generation CAR-T capabilities. Focus on solid tumor applications and off-the-shelf approaches.',
      marketPotential: '$20B+ by 2030',
      timeToImpact: 'Immediate',
    },
  },
  {
    id: 'tech-12',
    name: 'Checkpoint Inhibitors',
    shortDescription: 'PD-1/PD-L1 and CTLA-4 blockade',
    quadrant: 'therapeutic-approaches',
    ring: 'adopt',
    angle: 70,
    ringOffset: 0.5,
    therapeuticArea: 'oncology',
    opportunitySize: 'transformative',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Established standard of care across multiple cancers. Market consolidating but combination opportunities remain. Focus on next-generation targets.',
      keyPlayers: ['BMS', 'Merck', 'Roche', 'AstraZeneca'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Explore novel checkpoint targets (TIGIT, LAG-3) and combination strategies.',
      marketPotential: '$50B+ current market',
      timeToImpact: 'Immediate',
    },
  },
  {
    id: 'tech-13',
    name: 'CAR-NK Therapy',
    shortDescription: 'Off-the-shelf NK cell immunotherapy',
    quadrant: 'therapeutic-approaches',
    ring: 'trial',
    angle: 45,
    ringOffset: 0.4,
    therapeuticArea: 'oncology',
    opportunitySize: 'large',
    confidence: 'medium',
    detailedAssessment: {
      rationale: 'Potential advantages over CAR-T including off-the-shelf availability and improved safety. Early clinical data encouraging. Run POC studies.',
      keyPlayers: ['Fate Therapeutics', 'Nkarta', 'Artiva Biotherapeutics', 'Celularity'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Initiate CAR-NK program for liquid tumors. Partner for cell engineering expertise.',
      marketPotential: '$8B by 2032',
      timeToImpact: '3-4 years',
    },
  },
  {
    id: 'tech-14',
    name: 'In Vivo Gene Editing',
    shortDescription: 'Direct CRISPR editing in patients',
    quadrant: 'therapeutic-approaches',
    ring: 'assess',
    angle: 60,
    ringOffset: 0.6,
    therapeuticArea: 'rare-diseases',
    opportunitySize: 'transformative',
    confidence: 'medium',
    detailedAssessment: {
      rationale: 'First clinical successes in liver diseases. Delivery to other tissues remains challenging. Watch closely but wait for more safety data.',
      keyPlayers: ['Intellia', 'Editas', 'Beam Therapeutics', 'Verve Therapeutics'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Monitor clinical trial results. Consider partnerships for specific genetic diseases in 2-3 years.',
      marketPotential: '$15B+ by 2035',
      timeToImpact: '5-7 years',
    },
  },
  {
    id: 'tech-15',
    name: 'Senolytic Therapies',
    shortDescription: 'Elimination of senescent cells for aging diseases',
    quadrant: 'therapeutic-approaches',
    ring: 'monitor',
    angle: 80,
    ringOffset: 0.7,
    therapeuticArea: 'metabolic',
    opportunitySize: 'large',
    confidence: 'low',
    detailedAssessment: {
      rationale: 'Strong preclinical rationale but clinical validation lacking. Multiple failed trials. Needs more mechanistic understanding before significant investment.',
      keyPlayers: ['Unity Biotechnology', 'Rubedo Life Sciences', 'Oisín Biotechnologies'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Continue monitoring scientific literature. Revisit if breakthrough clinical data emerges.',
      marketPotential: 'Potentially massive but unproven',
      timeToImpact: '8-10 years',
    },
  },

  // ENABLING TOOLS QUADRANT (180-270°)
  {
    id: 'tech-16',
    name: 'Liquid Biopsy',
    shortDescription: 'Blood-based cancer detection and monitoring',
    quadrant: 'enabling-tools',
    ring: 'adopt',
    angle: 40,
    ringOffset: 0.3,
    therapeuticArea: 'oncology',
    opportunitySize: 'large',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'FDA-approved tests available. Proven utility for treatment selection and monitoring. Essential tool for precision oncology programs.',
      keyPlayers: ['Guardant Health', 'Foundation Medicine', 'Natera', 'GRAIL'],
      publications: [
        {
          title: 'Clinical utility of liquid biopsy in oncology',
          authors: 'Wan et al.',
          journal: 'Nature Reviews Cancer',
          year: 2024,
        },
      ],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Integrate into all oncology trials immediately. Partner for companion diagnostic development.',
      marketPotential: '$12B by 2030',
      timeToImpact: 'Immediate',
    },
  },
  {
    id: 'tech-17',
    name: 'PD-L1 Companion Diagnostics',
    shortDescription: 'IHC-based biomarker testing',
    quadrant: 'enabling-tools',
    ring: 'adopt',
    angle: 65,
    ringOffset: 0.5,
    therapeuticArea: 'oncology',
    opportunitySize: 'medium',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Standard companion diagnostic for checkpoint inhibitors. Well-validated across multiple indications.',
      keyPlayers: ['Agilent', 'Roche', 'Merck'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Continue use as standard biomarker. Explore complementary biomarkers for better patient selection.',
      marketPotential: 'Standard diagnostic',
      timeToImpact: 'Immediate',
    },
  },
  {
    id: 'tech-18',
    name: 'Multi-Omics Integration',
    shortDescription: 'Combined genomic, proteomic, metabolomic analysis',
    quadrant: 'enabling-tools',
    ring: 'trial',
    angle: 30,
    ringOffset: 0.4,
    therapeuticArea: 'cross-therapeutic',
    opportunitySize: 'large',
    confidence: 'medium',
    detailedAssessment: {
      rationale: 'Powerful approach for understanding disease biology but complex data analysis. Run on 2-3 key programs to validate utility.',
      keyPlayers: ['Seer', '10x Genomics', 'Illumina', 'Pacific Biosciences'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Deploy on early-stage discovery programs. Build bioinformatics capabilities for data integration.',
      marketPotential: '$6B by 2030',
      timeToImpact: '2-3 years',
    },
  },
  {
    id: 'tech-19',
    name: 'Spatial Transcriptomics',
    shortDescription: 'Location-aware gene expression profiling',
    quadrant: 'enabling-tools',
    ring: 'trial',
    angle: 55,
    ringOffset: 0.6,
    therapeuticArea: 'oncology',
    opportunitySize: 'medium',
    confidence: 'high',
    detailedAssessment: {
      rationale: 'Mature technology providing valuable tumor microenvironment insights. Multiple platforms available. Validate on immunotherapy programs.',
      keyPlayers: ['10x Genomics', 'NanoString', 'Vizgen'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Implement on oncology discovery and biomarker programs.',
      marketPotential: '$4B by 2029',
      timeToImpact: '1-2 years',
    },
  },
  {
    id: 'tech-20',
    name: 'Wearable Biosensors',
    shortDescription: 'Continuous patient monitoring devices',
    quadrant: 'enabling-tools',
    ring: 'monitor',
    angle: 75,
    ringOffset: 0.8,
    therapeuticArea: 'cardiovascular',
    opportunitySize: 'medium',
    confidence: 'low',
    detailedAssessment: {
      rationale: 'Consumer devices proliferating but clinical-grade validation limited. Regulatory pathway unclear. Monitor for decentralized trial applications.',
      keyPlayers: ['Apple', 'Abbott', 'Dexcom', 'Biofourmis'],
      publications: [],
      patents: [],
      clinicalTrials: [],
      recommendation: 'Monitor regulatory developments. Consider for specific DCT applications in 3-5 years.',
      marketPotential: '$8B by 2032',
      timeToImpact: '5-7 years',
    },
  },
];

export const getTherapeuticAreaColor = (area: string): string => {
  const colors: Record<string, string> = {
    'oncology': '#ef4444',
    'neurology': '#8b5cf6',
    'immunology': '#06b6d4',
    'cardiovascular': '#f97316',
    'rare-diseases': '#ec4899',
    'infectious-diseases': '#10b981',
    'metabolic': '#eab308',
    'cross-therapeutic': '#6366f1',
  };
  return colors[area] || '#6366f1';
};
