import { HorizonMetrics, TherapeuticLandscapePoint, CompetitorMove } from '@/types/pharmaHorizon';

export const mockHorizonMetrics: HorizonMetrics = {
  emergingMechanisms: { count: 23, change: 15.2 },
  therapeuticModalities: { count: 8, change: 12.5 },
  clinicalSignals: { count: 34, change: 28.7 },
  technologyShifts: { count: 12, change: 22.3 },
};

export const mockTherapeuticLandscape: TherapeuticLandscapePoint[] = [
  {
    id: 'tl-1',
    name: 'Bispecific Antibodies',
    patentActivity: 42,
    clinicalProgress: 28,
    totalPublications: 387,
    maturityStage: 'maturing',
    therapeuticArea: 'Oncology',
    modalityType: 'Antibody',
    aiInsight: 'Bispecific antibodies are rapidly maturing with strong patent activity and clinical momentum. Key players are moving beyond CD3 engagers into novel formats targeting tumor microenvironment. Competitive intensity is highest in hematologic malignancies.',
    details: {
      keyPlayers: ['AbbVie', 'Amgen', 'Regeneron'],
      recentPatents: ['US20250123456', 'US20250234567'],
      activeTrials: ['NCT05234567', 'NCT05345678'],
    },
  },
  {
    id: 'tl-2',
    name: 'CAR-NK Cell Therapy',
    patentActivity: 18,
    clinicalProgress: 12,
    totalPublications: 156,
    maturityStage: 'emerging',
    therapeuticArea: 'Oncology',
    modalityType: 'Cell Therapy',
    aiInsight: 'CAR-NK represents the next wave of cell therapy with advantages over CAR-T including off-the-shelf potential and reduced toxicity. Early clinical data is promising but manufacturing challenges remain. Patent landscape is less crowded than CAR-T.',
    details: {
      keyPlayers: ['Fate Therapeutics', 'Nkarta', 'Takeda'],
      recentPatents: ['US20250345678', 'US20250456789'],
      activeTrials: ['NCT05456789'],
    },
  },
  {
    id: 'tl-3',
    name: 'PROTAC Degraders',
    patentActivity: 35,
    clinicalProgress: 15,
    totalPublications: 298,
    maturityStage: 'growing',
    therapeuticArea: 'Oncology',
    modalityType: 'Small Molecule',
    aiInsight: 'PROTACs are transitioning from academic novelty to viable drug modality. Patent activity is intense with major pharma entering through partnerships. Oral bioavailability remains a key technical challenge affecting clinical progression.',
    details: {
      keyPlayers: ['Arvinas', 'Nurix', 'Bristol Myers Squibb'],
      recentPatents: ['US20250567890', 'US20250678901'],
      activeTrials: ['NCT05567890', 'NCT05678901'],
    },
  },
  {
    id: 'tl-4',
    name: 'mRNA Therapeutics',
    patentActivity: 28,
    clinicalProgress: 18,
    totalPublications: 412,
    maturityStage: 'growing',
    therapeuticArea: 'Oncology',
    modalityType: 'Nucleic Acid',
    aiInsight: 'Post-COVID, mRNA platforms are expanding into oncology with personalized cancer vaccines showing clinical promise. Delivery technology improvements are enabling broader therapeutic applications. Major pharma partnerships accelerating development.',
    details: {
      keyPlayers: ['Moderna', 'BioNTech', 'CureVac'],
      recentPatents: ['US20250789012', 'US20250890123'],
      activeTrials: ['NCT05789012', 'NCT05890123'],
    },
  },
  {
    id: 'tl-5',
    name: 'ADCs (3rd Gen)',
    patentActivity: 38,
    clinicalProgress: 32,
    totalPublications: 524,
    maturityStage: 'established',
    therapeuticArea: 'Oncology',
    modalityType: 'Antibody',
    aiInsight: 'Third-generation ADCs with novel linker-payload combinations and improved therapeutic windows are becoming standard of care in multiple tumor types. Patent estate is crowded requiring innovative differentiation strategies.',
    details: {
      keyPlayers: ['Daiichi Sankyo', 'AstraZeneca', 'Seagen'],
      recentPatents: ['US20250901234', 'US20251012345'],
      activeTrials: ['NCT05901234', 'NCT06012345'],
    },
  },
  {
    id: 'tl-6',
    name: 'AI-Designed Antibodies',
    patentActivity: 12,
    clinicalProgress: 4,
    totalPublications: 89,
    maturityStage: 'nascent',
    therapeuticArea: 'Oncology',
    modalityType: 'Antibody',
    aiInsight: 'Machine learning platforms are beginning to generate novel antibody scaffolds with improved properties. Early preclinical data is encouraging but clinical validation still years away. Computational approaches could dramatically reduce discovery timelines.',
    details: {
      keyPlayers: ['AbCellera', 'Absci', 'BigHat Biosciences'],
      recentPatents: ['US20251123456'],
      activeTrials: [],
    },
  },
  {
    id: 'tl-7',
    name: 'Gene Editing (In Vivo)',
    patentActivity: 24,
    clinicalProgress: 10,
    totalPublications: 267,
    maturityStage: 'emerging',
    therapeuticArea: 'Rare Disease',
    modalityType: 'Gene Therapy',
    aiInsight: 'In vivo gene editing moving beyond ex vivo CAR-T approaches. Delivery challenges being addressed through novel AAV capsids and LNP formulations. Regulatory pathway becoming clearer with recent approvals.',
    details: {
      keyPlayers: ['Intellia', 'Editas', 'Beam Therapeutics'],
      recentPatents: ['US20251234567', 'US20251345678'],
      activeTrials: ['NCT06123456', 'NCT06234567'],
    },
  },
  {
    id: 'tl-8',
    name: 'Checkpoint Inhibitors',
    patentActivity: 32,
    clinicalProgress: 38,
    totalPublications: 892,
    maturityStage: 'established',
    therapeuticArea: 'Oncology',
    modalityType: 'Antibody',
    aiInsight: 'Mature field with multiple approved agents. Innovation now focused on novel combinations and biomarker-driven patient selection. New targets beyond PD-1/LAG-3 showing early promise in resistant tumors.',
    details: {
      keyPlayers: ['Merck', 'Bristol Myers Squibb', 'Roche'],
      recentPatents: ['US20251456789', 'US20251567890'],
      activeTrials: ['NCT06345678', 'NCT06456789'],
    },
  },
  {
    id: 'tl-9',
    name: 'Microbiome Therapeutics',
    patentActivity: 16,
    clinicalProgress: 8,
    totalPublications: 178,
    maturityStage: 'emerging',
    therapeuticArea: 'Immunology',
    modalityType: 'Live Biotherapeutic',
    aiInsight: 'Rationally designed microbial consortia showing promise in enhancing immunotherapy response and reducing autoimmune disease activity. Manufacturing and regulatory hurdles remain significant. Early commercial success could catalyze investment.',
    details: {
      keyPlayers: ['Seres Therapeutics', 'Vedanta Biosciences', 'Finch Therapeutics'],
      recentPatents: ['US20251678901', 'US20251789012'],
      activeTrials: ['NCT06567890', 'NCT06678901'],
    },
  },
  {
    id: 'tl-10',
    name: 'Radiopharmaceuticals',
    patentActivity: 22,
    clinicalProgress: 16,
    totalPublications: 312,
    maturityStage: 'growing',
    therapeuticArea: 'Oncology',
    modalityType: 'Radiotherapy',
    aiInsight: 'Targeted alpha therapy gaining traction with improved tumor-to-normal tissue ratios. Prostate cancer success expanding to other solid tumors. Supply chain and manufacturing complexity limiting broader adoption.',
    details: {
      keyPlayers: ['Novartis', 'Point Biopharma', 'RayzeBio'],
      recentPatents: ['US20251890123', 'US20251901234'],
      activeTrials: ['NCT06789012', 'NCT06890123'],
    },
  },
  {
    id: 'tl-11',
    name: 'Neoantigen Vaccines',
    patentActivity: 20,
    clinicalProgress: 12,
    totalPublications: 234,
    maturityStage: 'emerging',
    therapeuticArea: 'Oncology',
    modalityType: 'Vaccine',
    aiInsight: 'Personalized cancer vaccines targeting patient-specific mutations showing improved response rates when combined with checkpoint inhibitors. Manufacturing turnaround time improvements making commercial viability more realistic.',
    details: {
      keyPlayers: ['BioNTech', 'Gritstone Bio', 'Neon Therapeutics'],
      recentPatents: ['US20252012345', 'US20252123456'],
      activeTrials: ['NCT06901234', 'NCT07012345'],
    },
  },
  {
    id: 'tl-12',
    name: 'Epigenetic Modulators',
    patentActivity: 26,
    clinicalProgress: 14,
    totalPublications: 356,
    maturityStage: 'growing',
    therapeuticArea: 'Oncology',
    modalityType: 'Small Molecule',
    aiInsight: 'Next-generation epigenetic drugs with improved selectivity showing activity in hematologic malignancies. Combination strategies with immunotherapy and targeted agents expanding indication potential.',
    details: {
      keyPlayers: ['Constellation Pharmaceuticals', 'Epizyme', 'C4 Therapeutics'],
      recentPatents: ['US20252234567', 'US20252345678'],
      activeTrials: ['NCT07123456', 'NCT07234567'],
    },
  },
  {
    id: 'tl-13',
    name: 'Oncolytic Viruses',
    patentActivity: 18,
    clinicalProgress: 14,
    totalPublications: 289,
    maturityStage: 'maturing',
    therapeuticArea: 'Oncology',
    modalityType: 'Biologic',
    aiInsight: 'Engineered viruses combining direct tumor lysis with immune activation gaining clinical traction. Combination with checkpoint inhibitors showing synergy. Manufacturing and delivery challenges being addressed.',
    details: {
      keyPlayers: ['Amgen', 'Replimune', 'Oncorus'],
      recentPatents: ['US20252456789', 'US20252567890'],
      activeTrials: ['NCT07345678', 'NCT07456789'],
    },
  },
  {
    id: 'tl-14',
    name: 'Bi/Tri-specific T-Cell Engagers',
    patentActivity: 36,
    clinicalProgress: 24,
    totalPublications: 445,
    maturityStage: 'maturing',
    therapeuticArea: 'Oncology',
    modalityType: 'Antibody',
    aiInsight: 'Multi-specific formats enabling more precise T-cell activation and reduced toxicity. Solid tumor penetration improving with novel engineering approaches. Half-life extension strategies enabling better dosing regimens.',
    details: {
      keyPlayers: ['Amgen', 'Regeneron', 'Johnson & Johnson'],
      recentPatents: ['US20252678901', 'US20252789012'],
      activeTrials: ['NCT07567890', 'NCT07678901'],
    },
  },
  {
    id: 'tl-15',
    name: 'Spatial Biology Platforms',
    patentActivity: 14,
    clinicalProgress: 6,
    totalPublications: 198,
    maturityStage: 'nascent',
    therapeuticArea: 'Oncology',
    modalityType: 'Diagnostic',
    aiInsight: 'High-resolution spatial transcriptomics and proteomics enabling unprecedented tumor microenvironment characterization. Biomarker discovery applications could transform patient selection strategies. Commercial assay development still early stage.',
    details: {
      keyPlayers: ['10x Genomics', 'Nanostring', 'Vizgen'],
      recentPatents: ['US20252890123', 'US20252901234'],
      activeTrials: [],
    },
  },
];

export const mockCompetitorMoves: CompetitorMove[] = [
  {
    id: 'cm-1',
    company: 'Bristol Myers Squibb',
    action: 'IND filing',
    description: 'IND submitted for BMS-986789, a novel LAG-3 x TIGIT bispecific antibody for advanced NSCLC and melanoma',
    date: new Date('2025-09-28'),
    therapeuticArea: 'Oncology',
    impact: 'high',
    aiAnalysis: 'Direct competitive threat to BCT-301. BMS has strong immuno-oncology expertise and fast development timelines. Their dual checkpoint approach validates our mechanism but accelerates competitive pressure. Recommend expediting BCT-301 Phase III enrollment and exploring differentiation through patient selection biomarkers.',
    relatedAssets: ['BCT-301'],
    trialId: 'NCT05789012',
  },
  {
    id: 'cm-2',
    company: 'Pfizer',
    action: 'Acquisition',
    description: 'Pfizer acquires Immunova Therapeutics ($340M upfront, $890M milestones) for lead STING agonist asset in solid tumors',
    date: new Date('2025-09-10'),
    therapeuticArea: 'Oncology',
    impact: 'high',
    aiAnalysis: 'Major validation of STING pathway with significant financial commitment from large pharma. Pfizer brings extensive oncology development capabilities and global reach. Creates both competitive pressure and partnership opportunity. Consider combination strategy with BCT-508 or explore differentiated mechanisms.',
    relatedAssets: ['BCT-508'],
  },
  {
    id: 'cm-3',
    company: 'Merck',
    action: 'Clinical data',
    description: 'Positive Phase III interim data: pembrolizumab + favezelimab (LAG-3) shows 52% ORR vs 38% control in melanoma (p=0.003)',
    date: new Date('2025-09-15'),
    therapeuticArea: 'Oncology',
    impact: 'high',
    aiAnalysis: 'Strong clinical validation of LAG-3 pathway in melanoma. Likely to accelerate FDA approval for this combo, establishing new standard of care. BCT-402 differentiation will need to focus on different indications (e.g., head/neck, gastric) or triple combination strategies. Monitor for FDA approval timeline.',
  },
  {
    id: 'cm-4',
    company: 'Moderna',
    action: 'Partnership',
    description: 'Moderna partners with AstraZeneca on personalized cancer vaccine platform, expanding into solid tumors beyond melanoma',
    date: new Date('2025-09-20'),
    therapeuticArea: 'Oncology',
    impact: 'medium',
    aiAnalysis: 'mRNA vaccine platforms gaining momentum with major pharma validation. Combination potential with our checkpoint inhibitors is significant. Suggests exploring partnership opportunities with mRNA companies for BCT-301 or BCT-402 combination trials.',
  },
  {
    id: 'cm-5',
    company: 'Roche',
    action: 'Phase transition',
    description: 'RG7986 (bispecific CD20xCD3) advances to Phase III in follicular lymphoma after strong Phase II data (78% ORR)',
    date: new Date('2025-09-05'),
    therapeuticArea: 'Oncology',
    impact: 'medium',
    aiAnalysis: 'Roche expanding T-cell engager portfolio beyond rituximab. Validates CD20 as enduring target in hematologic malignancies. Our BCT-205 program should monitor for potential combination opportunities or competitive positioning challenges.',
    relatedAssets: ['BCT-205'],
    trialId: 'NCT05901234',
  },
  {
    id: 'cm-6',
    company: 'Gilead',
    action: 'Patent filing',
    description: 'Novel oral STING agonist patent filed with improved bioavailability and reduced systemic inflammation',
    date: new Date('2025-08-28'),
    therapeuticArea: 'Oncology',
    impact: 'medium',
    aiAnalysis: 'Oral STING agonists could offer significant advantage over injectable formulations if safety profile is acceptable. Patent claims around specific chemical modifications may limit freedom to operate. Consider licensing discussions or alternative scaffold exploration.',
    patentNumber: 'WO2025089012',
  },
  {
    id: 'cm-7',
    company: 'AstraZeneca',
    action: 'Clinical data',
    description: 'Negative Phase III data for AZD9833 in HR+ breast cancer fails to meet primary endpoint (PFS: 8.2 vs 7.9 months, p=0.34)',
    date: new Date('2025-08-15'),
    therapeuticArea: 'Oncology',
    impact: 'low',
    aiAnalysis: 'Setback for next-gen SERDs validates challenges in this mechanism class. Opens opportunity window for alternative ER-targeting approaches. Our preclinical PROTAC program may benefit from reduced competitive pressure in near-term development timeline.',
  },
  {
    id: 'cm-8',
    company: 'Novartis',
    action: 'IND filing',
    description: 'IND for NVS-456 (KRAS G12C inhibitor) targeting NSCLC with novel binding mechanism distinct from sotorasib/adagrasib',
    date: new Date('2025-08-22'),
    therapeuticArea: 'Oncology',
    impact: 'high',
    aiAnalysis: 'Third-wave KRAS inhibitor entering clinic demonstrates continued innovation in this validated target. Patent landscape analysis needed to assess freedom to operate for our BCT-609 program. Novel binding mode may offer differentiation opportunity through combination strategies.',
    relatedAssets: ['BCT-609'],
    trialId: 'NCT06012345',
  },
  {
    id: 'cm-9',
    company: 'Amgen',
    action: 'Partnership',
    description: 'Strategic collaboration with Immatics ($150M upfront) for TCR-T cell therapy targeting multiple solid tumor neoantigens',
    date: new Date('2025-07-30'),
    therapeuticArea: 'Oncology',
    impact: 'medium',
    aiAnalysis: 'Major pharma commitment to personalized cell therapy validates commercial potential despite manufacturing complexity. TCR-T approaches may compete with or complement our CAR-T pipeline. Consider neoantigen vaccine combinations.',
  },
  {
    id: 'cm-10',
    company: 'Regeneron',
    action: 'Clinical data',
    description: 'Phase II data: REGN5458 (BCMAxCD3) shows 83% ORR in triple-class refractory multiple myeloma with manageable CRS',
    date: new Date('2025-07-18'),
    therapeuticArea: 'Oncology',
    impact: 'high',
    aiAnalysis: 'Best-in-class efficacy data for BCMA-targeted bispecific. Sets new benchmark for our BCT-705 development program. Differentiation strategy should focus on earlier lines of therapy or combination with novel immunomodulators to avoid head-to-head comparison.',
    relatedAssets: ['BCT-705'],
  },
  {
    id: 'cm-11',
    company: 'Johnson & Johnson',
    action: 'Acquisition',
    description: 'Acquires Ambrx Biopharma ($2B) for proprietary ADC platform with non-natural amino acid technology',
    date: new Date('2025-07-05'),
    therapeuticArea: 'Oncology',
    impact: 'medium',
    aiAnalysis: 'Significant premium paid for differentiated ADC technology validates next-gen conjugation approaches. Platform acquisition strategy suggests J&J building comprehensive oncology capabilities. May create partnership opportunities or competitive pressure depending on target overlap.',
  },
  {
    id: 'cm-12',
    company: 'Eli Lilly',
    action: 'Phase transition',
    description: 'LY3537982 (oral GLP-1/GIP dual agonist) advances to Phase III for obesity after positive Phase II (18% weight loss vs 3% placebo)',
    date: new Date('2025-06-20'),
    therapeuticArea: 'Metabolic',
    impact: 'low',
    aiAnalysis: 'Oral formulation represents major advancement over injectable GLP-1 therapies. While outside our core focus, demonstrates pathway to oral delivery of peptide-like drugs. Technology may have applicability to our peptide therapeutics in development.',
  },
  {
    id: 'cm-13',
    company: 'Sanofi',
    action: 'Patent filing',
    description: 'Composition of matter patent for IL-2 receptor beta-gamma selective agonist with minimal alpha engagement',
    date: new Date('2025-06-12'),
    therapeuticArea: 'Oncology',
    impact: 'medium',
    aiAnalysis: 'Novel IL-2 engineering approach addresses long-standing toxicity concerns. Potential competition for our BCT-808 program but also validates therapeutic rationale. Claim scope assessment needed to determine impact on development strategy.',
    patentNumber: 'WO2025067890',
  },
  {
    id: 'cm-14',
    company: 'AbbVie',
    action: 'Clinical data',
    description: 'ABBV-383 (BCMAxCD3) Phase I expansion: 77% ORR in relapsed/refractory multiple myeloma, lower CRS rates than competitors',
    date: new Date('2025-06-01'),
    therapeuticArea: 'Oncology',
    impact: 'high',
    aiAnalysis: 'Differentiated safety profile could be key commercial differentiator in crowded BCMA bispecific space. AbbVie\'s development speed and commercial execution capabilities make them formidable competitor. BCT-705 needs clear value proposition beyond efficacy.',
    relatedAssets: ['BCT-705'],
  },
  {
    id: 'cm-15',
    company: 'Takeda',
    action: 'Partnership',
    description: 'Collaboration with Evotec ($80M upfront) to discover novel targeted protein degraders for oncology and neurology',
    date: new Date('2025-05-28'),
    therapeuticArea: 'Oncology',
    impact: 'low',
    aiAnalysis: 'PROTAC platform partnerships accelerating as modality gains validation. Takeda bringing significant development and commercial capabilities to degrader space. Monitor for target overlap with our BCT-910 PROTAC program and potential collaboration opportunities.',
  },
];
